#!/usr/bin/env python3
"""Generate seed-blog-posts.json with 12 skylift-rental articles in EN/MS/ZH."""
import json, os, sys

OUT = "/Users/intern/Documents/GitHub/utopia-website-system/projects/skylift-malaysia/scripts/seed-blog-posts.json"

PEXELS = lambda i: f"https://images.pexels.com/photos/{i}/pexels-photo-{i}.jpeg?auto=compress&cs=tinysrgb&w=1200"

# Common helpers — produce locale-correct WhatsApp CTA + internal links
def cta(locale):
    label = {"en": "WhatsApp Booking Now", "ms": "WhatsApp Tempahan Sekarang", "zh": "立即 WhatsApp 预订"}[locale]
    return f'<p><a href="/{locale}/redirect-whatsapp-1" class="btn btn-wa btn-lg">{label}</a></p>'

def home_link(locale, label):
    return f'<a href="/{locale}/">{label}</a>'

def loc_link(locale, slug, label):
    return f'<a href="/{locale}/skylift/{slug}">{label}</a>'

def toc(locale, items):
    label = {"en": "What's inside", "ms": "Kandungan artikel", "zh": "目录"}[locale]
    lis = "".join(f'<li><a href="#{i}">{t}</a></li>' for i, t in items)
    return f'<div class="toc"><strong>{label}</strong><ul>{lis}</ul></div>'

def img(pid, alt):
    return f'<img src="{PEXELS(pid)}" alt="{alt}" loading="lazy" />'

# ===== ARTICLE 1 — Choose the right skylift =====
A1 = {
    "slug": "choose-the-right-skylift-9m-vs-20m-vs-24m-vs-32m",
    "cover": PEXELS(1216597),
    "en": {
        "title": "How to Choose the Right Skylift — 9m vs 20m vs 24m vs 32m",
        "excerpt": "Match your job height to the right skylift size. Compact 9m for indoor, 20m–24m for shoplots, 32m for stadium and billboard work.",
        "meta_title": "How to Choose the Right Skylift Size — Skylift Malaysia",
        "meta_desc": "Pick the correct skylift size for your job. 9m, 20m, 24m, 32m boom comparison, with Malaysian site examples and rental costs.",
        "body": f"""
{toc('en', [('intro','Introduction'),('size-guide','Skylift Sizing Guide'),('cost','Cost by Size'),('cta','Ready to book?'),('faq','FAQ'),('conclusion','Conclusion')])}

<h2 id="intro">Introduction</h2>
<p>Choosing the wrong skylift size is the most common (and most expensive) mistake new contractors make. Too small — you can't reach the work and have to re-book the next size up. Too big — you pay for capacity you don't need and may not even fit it through the gate.</p>
<p>This guide walks you through the four most-rented sizes in Malaysia: 9-metre, 20-metre, 24-metre, and 32-metre boom lifts, with real site examples for each.</p>
{img(1216544, 'Skylift truck on Malaysian construction site')}

<h2 id="size-guide">Skylift Sizing Guide</h2>
<h3>9m Skylift — Indoor & Confined Spaces</h3>
<p>The 9-metre electric skylift is built for indoor use. Zero emissions, quiet operation, and a chassis narrow enough to roll through standard double doorways. Use it for ceiling work in malls, warehouse high-bays, factory ducting, and atrium maintenance.</p>
<p>Typical jobs: HVAC duct cleaning, sprinkler-head installation, mall ceiling repaint, indoor billboard install. Daily rate: <strong>RM380</strong>. Operator and insurance always included.</p>

<h3>20m Skylift — The Workhorse</h3>
<p>The 20-metre diesel boom is our most-rented unit. It handles 90% of shop-front signage, AC servicing on commercial buildings, billboard installs, and tree-pruning along town roads.</p>
<p>It's truck-mounted, drives at full road speed, and deploys in under 5 minutes once on-site. Half-day pricing kicks in at <strong>RM500</strong> (great for short jobs); a full day is <strong>RM620</strong>.</p>
<p>If you're doing typical "tukar lampu" or "pasang banner" work in {loc_link('en','kuala-lumpur','Kuala Lumpur')} or {loc_link('en','petaling-jaya','Petaling Jaya')}, this is your default.</p>

<h3>24m Skylift — High-Rise Facade</h3>
<p>The 24-metre boom adds reach for taller commercial buildings, factory rooftops, and residential high-rise facades. Same diesel platform as the 20m, with longer outriggers for stability at full extension.</p>
<p>Half-day <strong>RM500</strong>, full day <strong>RM650</strong>. Often the right call for warehouse roofing in {loc_link('en','shah-alam','Shah Alam')} or factory roof inspection in industrial estates.</p>

<h3>32m Skylift — Stadium & Billboard</h3>
<p>The 32-metre is heavy-reach territory. Stadium light replacement, large highway billboards, tall industrial chimneys. Truck-mounted with full counterweight outriggers.</p>
<p>Pricing is quote-on-demand because access logistics matter — outriggers need clear ground around the chassis, and travel routes must clear underpasses.</p>

<h2 id="cost">Cost Comparison Snapshot</h2>
<blockquote>9m: RM380/day · 20m: RM500 half/RM620 full · 24m: RM500 half/RM650 full · 32m: from RM1,200/day. All include certified operator and insurance.</blockquote>
<p>Half-day pricing on the 20m and 24m is the best-kept secret in the industry — perfect for a 3-hour signage swap.</p>

<h2 id="cta">Ready to Book?</h2>
<p>Tell us the height, location, and job type — we'll dispatch the right unit. {home_link('en','See all our skylift units')} or chat now:</p>
{cta('en')}

<h2 id="faq">FAQ</h2>
<h3>Can I use a 20m skylift indoors?</h3>
<p>No — diesel units exhaust fumes and are too tall for most indoor ceilings. Use the 9m electric or the spider lift instead.</p>
<h3>Do I need a permit?</h3>
<p>For private property, no. For roadside work in KL/Selangor, you may need DBKL or MBPJ approval. Our operator can advise.</p>

<h2 id="conclusion">Conclusion</h2>
<p>Match the height to the job, not the other way around. WhatsApp us with your site address and what you need to reach — we'll quote within 5 minutes.</p>
{cta('en')}
"""
    },
    "ms": {
        "title": "Cara Pilih Skylift Yang Betul — 9m vs 20m vs 24m vs 32m",
        "excerpt": "Padankan ketinggian kerja anda dengan saiz skylift yang sesuai. 9m untuk dalam bangunan, 20m–24m untuk kedai, 32m untuk papan iklan.",
        "meta_title": "Cara Pilih Saiz Skylift — Skylift Malaysia",
        "meta_desc": "Panduan pilih saiz skylift untuk projek anda. Bandingan 9m, 20m, 24m, 32m dengan contoh tapak dan kos sewa di Malaysia.",
        "body": f"""
{toc('ms', [('intro','Pengenalan'),('size-guide','Panduan Saiz Skylift'),('cost','Kos Mengikut Saiz'),('cta','Sedia tempah?'),('faq','Soalan Lazim'),('conclusion','Penutup')])}

<h2 id="intro">Pengenalan</h2>
<p>Memilih saiz skylift yang salah adalah kesilapan paling biasa (dan paling mahal) bagi kontraktor baru. Terlalu kecil — kerja tak sampai dan kena tempah unit lebih besar. Terlalu besar — bayar lebih untuk kapasiti yang tak guna, malah ada kalanya tak masuk pintu pagar tapak.</p>
<p>Panduan ini menerangkan empat saiz paling laris di Malaysia: skylift 9m, 20m, 24m, dan 32m, dengan contoh kerja sebenar untuk setiap satu.</p>
{img(1216544, 'Skylift di tapak pembinaan Malaysia')}

<h2 id="size-guide">Panduan Saiz Skylift</h2>
<h3>Skylift 9m — Dalam Bangunan & Ruang Sempit</h3>
<p>Skylift elektrik 9-meter dibina khas untuk kerja dalam bangunan. Tiada gas ekzos, operasi senyap, dan badan unit cukup nipis untuk lalu pintu dua-helai biasa. Sesuai untuk siling pasaraya, gudang tinggi, ducting kilang, dan kerja atrium.</p>
<p>Kerja tipikal: cuci ducting HVAC, pasang kepala sprinkler, cat siling pasaraya, papan iklan dalam mall. Kadar harian: <strong>RM380</strong>. Operator dan insurans sentiasa termasuk.</p>

<h3>Skylift 20m — Unit Paling Laris</h3>
<p>Skylift diesel 20-meter ialah unit paling laris kami. Ia uruskan 90% kerja papan kedai, servis aircond komersial, pasang papan iklan, dan pemangkasan pokok di tepi jalan.</p>
<p>Dipasang atas trak, boleh memandu pada kelajuan jalan biasa, dan boleh disusun atur dalam 5 minit di tapak. Harga separuh hari bermula <strong>RM500</strong> (sesuai untuk kerja pendek); satu hari penuh <strong>RM620</strong>.</p>
<p>Kalau anda buat kerja "tukar lampu" atau "pasang banner" di {loc_link('ms','kuala-lumpur','Kuala Lumpur')} atau {loc_link('ms','petaling-jaya','Petaling Jaya')}, inilah pilihan asas.</p>

<h3>Skylift 24m — Fasad Bangunan Tinggi</h3>
<p>Boom 24-meter memberi capaian tambahan untuk bangunan komersial yang lebih tinggi, bumbung kilang, dan fasad pangsapuri. Platform diesel yang sama dengan 20m, dengan outrigger lebih panjang untuk kestabilan ketika boom dipanjangkan penuh.</p>
<p>Separuh hari <strong>RM500</strong>, satu hari penuh <strong>RM650</strong>. Selalunya pilihan tepat untuk bumbung gudang di {loc_link('ms','shah-alam','Shah Alam')} atau pemeriksaan bumbung kilang di kawasan perindustrian.</p>

<h3>Skylift 32m — Stadium & Papan Iklan Besar</h3>
<p>32-meter ialah kawasan capaian berat. Tukar lampu stadium, papan iklan jalan raya besar, cerobong industri tinggi. Dipasang atas trak dengan outrigger pengimbang penuh.</p>
<p>Harga ikut sebut-harga sebab logistik akses penting — outrigger perlu ruang lapang sekeliling chassis, dan laluan perlu lulus ketinggian jambatan.</p>

<h2 id="cost">Bandingan Kos Ringkas</h2>
<blockquote>9m: RM380/hari · 20m: RM500 separuh/RM620 penuh · 24m: RM500 separuh/RM650 penuh · 32m: dari RM1,200/hari. Semua termasuk operator bertauliah dan insurans.</blockquote>
<p>Kadar separuh hari pada 20m dan 24m adalah rahsia industri — sangat sesuai untuk tukar papan tanda 3 jam.</p>

<h2 id="cta">Sedia Tempah?</h2>
<p>Beritahu kami ketinggian, lokasi, dan jenis kerja — kami akan hantar unit yang betul. {home_link('ms','Lihat semua unit skylift kami')} atau berbual sekarang:</p>
{cta('ms')}

<h2 id="faq">Soalan Lazim</h2>
<h3>Boleh saya guna skylift 20m dalam bangunan?</h3>
<p>Tidak — unit diesel keluarkan asap dan terlalu tinggi untuk kebanyakan siling. Guna 9m elektrik atau spider lift sebagai alternatif.</p>
<h3>Perlu permit ke?</h3>
<p>Untuk hartanah persendirian, tidak. Untuk kerja tepi jalan KL/Selangor, mungkin perlu kelulusan DBKL atau MBPJ. Operator kami boleh nasihatkan.</p>

<h2 id="conclusion">Penutup</h2>
<p>Padankan ketinggian dengan kerja, bukan sebaliknya. WhatsApp kami dengan alamat tapak dan apa yang anda perlu capai — kami akan beri sebut-harga dalam 5 minit.</p>
{cta('ms')}
"""
    },
    "zh": {
        "title": "如何选择合适的高空车 — 9m vs 20m vs 24m vs 32m",
        "excerpt": "根据作业高度选择合适的高空车尺寸。9m 适合室内、20m–24m 适合店面、32m 适合体育场和广告牌工程。",
        "meta_title": "如何选择高空车尺寸 — Skylift Malaysia",
        "meta_desc": "选择合适尺寸的高空车。9m、20m、24m、32m boom 比较，附马来西亚现场实例和租用费用。",
        "body": f"""
{toc('zh', [('intro','简介'),('size-guide','尺寸指南'),('cost','尺寸费用对比'),('cta','准备预订?'),('faq','常见问题'),('conclusion','总结')])}

<h2 id="intro">简介</h2>
<p>选错高空车尺寸是新承包商最常见(也最昂贵)的错误。太小 — 工作够不着,得加订更大的;太大 — 多花钱不说,可能连工地大门都进不去。</p>
<p>本指南介绍马来西亚最常租用的四种尺寸:9 米、20 米、24 米和 32 米臂式高空车,并附每种尺寸的实际工程案例。</p>
{img(1216544, '马来西亚工地的高空车')}

<h2 id="size-guide">尺寸指南</h2>
<h3>9m 高空车 — 室内与狭窄空间</h3>
<p>9 米电动高空车专为室内作业设计。零排放、运行安静,底盘窄到能从标准双开门通过。适合商场天花板维修、仓库高架、工厂通风管道、中庭维护。</p>
<p>典型用途:HVAC 风管清洁、洒水器头安装、商场天花板重绘、室内广告牌安装。日租:<strong>RM380</strong>。每次都包含操作员和保险。</p>

<h3>20m 高空车 — 主力机型</h3>
<p>20 米柴油臂式机是我们最受欢迎的机型。它能应付 90% 的店面招牌、商业楼空调维修、广告牌安装、街道树木修剪等工作。</p>
<p>卡车装载式,可正常公路速度行驶,到场后 5 分钟内即可展开。半天定价 <strong>RM500</strong>(适合短工);全天 <strong>RM620</strong>。</p>
<p>如果您在 {loc_link('zh','kuala-lumpur','吉隆坡')} 或 {loc_link('zh','petaling-jaya','八打灵再也')} 做"换灯"或"挂横幅"工作,这就是您的首选。</p>

<h3>24m 高空车 — 高层立面</h3>
<p>24 米臂式增加了对更高商业楼、工厂屋顶和高层公寓立面的覆盖。与 20m 同款柴油平台,但配备更长的支腿以在臂全伸时保持稳定。</p>
<p>半天 <strong>RM500</strong>,全天 <strong>RM650</strong>。常用于 {loc_link('zh','shah-alam','莎阿南')} 仓库屋顶或工业区工厂屋顶检查。</p>

<h3>32m 高空车 — 体育场与大广告牌</h3>
<p>32 米属重型作业范畴。体育场灯具更换、高速公路大广告牌、高大工业烟囱。卡车装载并配有完整配重支腿。</p>
<p>价格按需报价,因为接入物流很重要 — 支腿需要底盘周围有空地,行驶路线需通过桥洞高度限制。</p>

<h2 id="cost">费用速览</h2>
<blockquote>9m: RM380/天 · 20m: RM500 半天 / RM620 全天 · 24m: RM500 半天 / RM650 全天 · 32m: 从 RM1,200/天起。均含持证操作员与保险。</blockquote>
<p>20m 和 24m 的半天定价是行业内的最佳秘密 — 非常适合 3 小时换招牌的短工。</p>

<h2 id="cta">准备预订?</h2>
<p>告诉我们高度、地点和工作类型 — 我们将派遣合适的机型。{home_link('zh','查看我们所有高空车机型')} 或现在咨询:</p>
{cta('zh')}

<h2 id="faq">常见问题</h2>
<h3>20m 高空车能在室内使用吗?</h3>
<p>不能 — 柴油机会排放废气,且大部分室内天花太矮。请改用 9m 电动机或蜘蛛车。</p>
<h3>需要许可证吗?</h3>
<p>私人物业不需要。KL/雪兰莪的路边作业可能需要 DBKL 或 MBPJ 批准。我们的操作员可提供建议。</p>

<h2 id="conclusion">总结</h2>
<p>让高度匹配工作,而非反过来。WhatsApp 联系我们提供工地地址和所需高度 — 我们会在 5 分钟内报价。</p>
{cta('zh')}
"""
    },
}

# ===== Article 2 — Skylift rental cost =====
A2 = {
    "slug": "skylift-rental-cost-malaysia-2026-daily-weekly-monthly-rates",
    "cover": PEXELS(159306),
    "en": {"title":"Skylift Rental Cost Malaysia 2026 — Daily, Weekly & Monthly Rates","excerpt":"Up-to-date 2026 skylift rental rates across Malaysia. Half-day, daily, weekly and monthly pricing for 9m, 20m, 24m, 32m and spider lifts.","meta_title":"Skylift Rental Cost Malaysia 2026 — Live Rates","meta_desc":"2026 skylift rental rates: half-day from RM500, full day from RM380, weekly and monthly bundles. Operator and insurance always included.",
    "body": f"""{toc('en',[('intro','Introduction'),('rates','Daily & Half-Day Rates'),('weekly','Weekly & Monthly'),('cta','Ready to book?'),('hidden','Hidden Costs to Avoid'),('conclusion','Conclusion')])}
<h2 id="intro">Introduction</h2><p>Skylift rental in Malaysia ranges from RM380 a day for the smallest indoor unit to RM1,200+ for the 32-metre boom. This guide covers every published rate for 2026 — including the half-day pricing most contractors overlook.</p><p>All rates below include a CIDB-certified operator, full insurance coverage, and delivery within KL & Selangor. {home_link('en','See our full unit catalogue here')}.</p>{img(1108572,'Skylift truck deployed at Malaysian shopfront')}
<h2 id="rates">Daily & Half-Day Rates</h2><h3>9m Skylift — RM380/day</h3><p>Indoor electric unit. Daily-only — no half-day option because deployment time inside buildings doesn't compress well. Quiet, zero-emission, fits standard double doorways.</p><h3>20m Skylift — RM500 half / RM620 full</h3><p>The half-day rate is the secret weapon for shopfront work. If your job is under 4 hours, you save RM120 vs the full-day rate. Most "tukar lampu" or "pasang banner" jobs in {loc_link('en','petaling-jaya','Petaling Jaya')} fit comfortably in half a day.</p><h3>24m Skylift — RM500 half / RM650 full</h3><p>Same half-day pricing as 20m, but with 4 extra metres of reach — useful for 4-storey buildings and large industrial signage.</p><h3>32m Skylift — from RM1,200/day</h3><p>Quote-on-demand because access logistics matter. Stadium lighting, tall billboard, factory chimneys.</p><h3>Spider Skylift — RM850/day</h3><p>The narrow-track unit for indoor reach work that 9m can't handle. Atrium glazing, mall ceiling repaint over fixtures.</p>
<h2 id="weekly">Weekly & Monthly Bundles</h2><blockquote>Weekly bundles save 15–20%. Monthly bundles save 30–35%. Available on 9m, 20m, 24m units. Spider and 32m are quote-only.</blockquote><p>For long-running renovation projects (mall refit, warehouse construction), the monthly rate is what makes the maths work. Operator hours within working week are included; weekend work charges apply only after 6pm Saturday.</p>
<h2 id="cta">Ready to Book?</h2><p>Tell us your job dates and the unit — we'll quote within 5 minutes.</p>{cta('en')}
<h2 id="hidden">Hidden Costs to Avoid</h2><h3>Outrigger ground prep</h3><p>If your site has soft soil, you'll need outrigger pads (RM50/day each) — quote them up-front so there are no surprises.</p><h3>Permit fees</h3><p>Roadside work in DBKL/MBPJ areas may require local-council permit (RM150–RM350). Our operator can handle the application — request it when you book.</p>
<h2 id="conclusion">Conclusion</h2><p>Skylift rental pricing is straightforward when you know which size you need. WhatsApp us with the job height and address, we'll confirm a fixed quote in 5 minutes.</p>{cta('en')}"""},
    "ms": {"title":"Kos Sewa Skylift Malaysia 2026 — Kadar Harian, Mingguan & Bulanan","excerpt":"Kadar sewa skylift terkini 2026 di seluruh Malaysia. Harga separuh hari, harian, mingguan dan bulanan untuk 9m, 20m, 24m, 32m dan spider lift.","meta_title":"Kos Sewa Skylift Malaysia 2026 — Kadar Terkini","meta_desc":"Kadar sewa skylift 2026: separuh hari dari RM500, harian dari RM380, pakej mingguan dan bulanan. Operator dan insurans sentiasa termasuk.",
    "body": f"""{toc('ms',[('intro','Pengenalan'),('rates','Kadar Harian & Separuh Hari'),('weekly','Mingguan & Bulanan'),('cta','Sedia tempah?'),('hidden','Kos Tersembunyi'),('conclusion','Penutup')])}
<h2 id="intro">Pengenalan</h2><p>Sewa skylift di Malaysia bermula dari RM380 sehari untuk unit dalaman terkecil hingga RM1,200+ untuk boom 32-meter. Panduan ini meliputi setiap kadar 2026 — termasuk kadar separuh hari yang ramai kontraktor terlepas pandang.</p><p>Semua kadar di bawah termasuk operator bertauliah CIDB, perlindungan insurans penuh, dan penghantaran dalam KL & Selangor. {home_link('ms','Lihat katalog unit penuh kami di sini')}.</p>{img(1108572,'Skylift di tapak kedai Malaysia')}
<h2 id="rates">Kadar Harian & Separuh Hari</h2><h3>Skylift 9m — RM380/hari</h3><p>Unit elektrik dalaman. Harian sahaja — tiada separuh hari kerana masa pasang dalam bangunan susah dimampatkan. Senyap, tiada asap, muat pintu dua-helai standard.</p><h3>Skylift 20m — RM500 separuh / RM620 penuh</h3><p>Kadar separuh hari ialah senjata rahsia untuk kerja papan kedai. Kalau kerja anda di bawah 4 jam, anda jimat RM120 berbanding kadar penuh. Kebanyakan kerja "tukar lampu" atau "pasang banner" di {loc_link('ms','petaling-jaya','Petaling Jaya')} muat dalam separuh hari.</p><h3>Skylift 24m — RM500 separuh / RM650 penuh</h3><p>Kadar separuh hari sama dengan 20m, tetapi 4 meter capaian tambahan — sesuai untuk bangunan 4 tingkat dan papan tanda industri besar.</p><h3>Skylift 32m — dari RM1,200/hari</h3><p>Sebut-harga ikut keadaan kerana logistik akses penting. Lampu stadium, papan iklan tinggi, cerobong kilang.</p><h3>Spider Skylift — RM850/hari</h3><p>Unit trek nipis untuk kerja capaian dalaman yang 9m tak boleh urus. Glazing atrium, cat siling pasaraya.</p>
<h2 id="weekly">Pakej Mingguan & Bulanan</h2><blockquote>Pakej mingguan jimat 15–20%. Pakej bulanan jimat 30–35%. Tersedia untuk unit 9m, 20m, 24m. Spider dan 32m sebut-harga sahaja.</blockquote><p>Untuk projek renovasi panjang (renovasi pasaraya, pembinaan gudang), kadar bulanan yang menjadikan kira-kira berjalan. Jam operator dalam minggu kerja termasuk; caj kerja hujung minggu hanya bermula selepas 6 petang Sabtu.</p>
<h2 id="cta">Sedia Tempah?</h2><p>Beritahu kami tarikh kerja dan unit — kami akan beri sebut-harga dalam 5 minit.</p>{cta('ms')}
<h2 id="hidden">Kos Tersembunyi</h2><h3>Persediaan tanah outrigger</h3><p>Kalau tapak tanah lembut, anda perlukan pad outrigger (RM50/hari setiap satu) — sebut awal supaya tiada kejutan.</p><h3>Yuran permit</h3><p>Kerja tepi jalan kawasan DBKL/MBPJ mungkin perlu permit majlis tempatan (RM150–RM350). Operator kami boleh uruskan — minta bila tempah.</p>
<h2 id="conclusion">Penutup</h2><p>Kadar sewa skylift mudah faham bila anda tahu saiz yang perlu. WhatsApp kami dengan ketinggian dan alamat — kami sahkan sebut-harga tetap dalam 5 minit.</p>{cta('ms')}"""},
    "zh": {"title":"马来西亚高空车租用费用 2026 — 日租、周租、月租","excerpt":"2026 马来西亚高空车最新租用费率。9m、20m、24m、32m 和蜘蛛车的半天、日租、周租、月租定价。","meta_title":"马来西亚高空车租用费 2026 — 最新费率","meta_desc":"2026 高空车租用费率:半天起 RM500,全天起 RM380,周租和月租套餐。每次都含操作员与保险。",
    "body": f"""{toc('zh',[('intro','简介'),('rates','日租与半天费率'),('weekly','周租与月租'),('cta','准备预订?'),('hidden','隐藏成本'),('conclusion','总结')])}
<h2 id="intro">简介</h2><p>马来西亚高空车租用从最小室内机型每天 RM380 到 32 米臂式机 RM1,200+ 不等。本指南涵盖 2026 年所有公开费率 — 包括许多承包商忽略的半天定价。</p><p>以下所有费率均包含 CIDB 持证操作员、全险保障,以及在 KL 和雪兰莪范围内的送达。{home_link('zh','查看我们的完整机型目录')}.</p>{img(1108572,'部署在马来西亚店面的高空车')}
<h2 id="rates">日租与半天费率</h2><h3>9m 高空车 — RM380/天</h3><p>室内电动机型。仅日租 — 无半天选项,因为室内部署时间难以压缩。安静、零排放、可通过标准双开门。</p><h3>20m 高空车 — 半天 RM500 / 全天 RM620</h3><p>半天费率是店面工程的秘密武器。若您工作不到 4 小时,与全天费率相比可节省 RM120。{loc_link('zh','petaling-jaya','八打灵再也')} 的"换灯"或"挂横幅"工作大多半天足够。</p><h3>24m 高空车 — 半天 RM500 / 全天 RM650</h3><p>半天定价与 20m 相同,但多 4 米伸展 — 适合 4 层楼建筑和大型工业招牌。</p><h3>32m 高空车 — 起 RM1,200/天</h3><p>按需报价,因为接入物流很重要。体育场灯具、高广告牌、工厂烟囱。</p><h3>蜘蛛高空车 — RM850/天</h3><p>窄履带机型,处理 9m 无法应付的室内伸展工作。中庭玻璃、商场天花板重绘。</p>
<h2 id="weekly">周租与月租套餐</h2><blockquote>周租套餐节省 15–20%。月租套餐节省 30–35%。适用于 9m、20m、24m 机型。蜘蛛车与 32m 仅按需报价。</blockquote><p>对于长期翻新项目(商场改造、仓库建设),月租价格才能让数学算得过来。工作日内的操作员工时包含在内;周末工作仅在周六晚 6 点后产生附加费。</p>
<h2 id="cta">准备预订?</h2><p>告诉我们工期和机型 — 我们 5 分钟内报价。</p>{cta('zh')}
<h2 id="hidden">隐藏成本</h2><h3>支腿地面准备</h3><p>若工地土质松软,您需要支腿垫板(每天每块 RM50)— 提前提出以免有意外。</p><h3>许可证费</h3><p>DBKL/MBPJ 区域的路边作业可能需要市政府许可证(RM150–RM350)。我们的操作员可代办 — 预订时告知即可。</p>
<h2 id="conclusion">总结</h2><p>知道所需尺寸后,高空车租用定价就很清楚。WhatsApp 联系我们告知工程高度和地址 — 我们 5 分钟内确认固定报价。</p>{cta('zh')}"""}
}

# ===== Article 3 — Safety mistakes =====
A3 = {"slug":"5-skylift-safety-mistakes-that-cause-site-accidents","cover":PEXELS(1216544),
"en":{"title":"5 Skylift Safety Mistakes That Cause Site Accidents","excerpt":"The five mistakes site supervisors keep making with skylift rentals — and how to fix each one before someone gets hurt.","meta_title":"5 Skylift Safety Mistakes (and How to Fix Them) — Skylift Malaysia","meta_desc":"Skylift safety mistakes Malaysian sites repeat: ignoring outriggers, wind speed, harness anchor, capacity limit, ground bearing.","body":f"""{toc('en',[('intro','Introduction'),('mistakes','The Five Mistakes'),('checklist','Pre-Use Checklist'),('cta','Ready to book?'),('conclusion','Conclusion')])}<h2 id="intro">Introduction</h2><p>Skylift accidents in Malaysia are rarely caused by faulty equipment. They're caused by site teams skipping basic safety steps because the job feels routine. Below are the five most common mistakes — review them before your next deployment.</p>{img(159306,'Site supervisor inspecting skylift before lifting')}<h2 id="mistakes">The Five Mistakes</h2><h3>1. Skipping outrigger deployment</h3><p>"It's just a small lift, we don't need outriggers." This is the #1 cause of tip-overs. Every truck-mounted boom needs all four outriggers fully extended and locked, on firm ground, before the basket leaves the cradle.</p><h3>2. Ignoring wind speed</h3><p>Above 12.5 m/s (about 28 mph), boom lifts must be lowered. Many supervisors don't even check. A pocket anemometer costs RM80 — buy one.</p><h3>3. No harness anchor inside the basket</h3><p>The harness clips to the basket anchor point, never to the structure outside. If the basket falls, an external anchor turns the worker into a pendulum.</p><h3>4. Exceeding capacity</h3><p>Most skylifts cap at 230 kg. Two workers + tools + a roll of cable can hit that fast. Read the capacity decal before you load up.</p><h3>5. Soft ground without pads</h3><p>Outriggers sink into asphalt on hot days and into wet soil after rain. Use steel or hardwood pads under each leg whenever the ground isn't reinforced concrete.</p><h2 id="checklist">Pre-Use Checklist</h2><blockquote>Outriggers · Wind · Harness · Capacity · Ground · Operator certs · Emergency lower control · Fuel level · Tyre pressure · Site permit</blockquote><p>Run this list every morning, no exceptions. Our operators do it before every booking — your supervisor should sign off too.</p><h2 id="cta">Ready to Book?</h2><p>Every Skylift Malaysia rental includes a CIDB-certified operator who runs the safety checklist with your supervisor. {home_link('en','See our fleet')} or chat:</p>{cta('en')}<h2 id="conclusion">Conclusion</h2><p>Safety isn't paperwork — it's five checks that take 90 seconds. Skip them and the consequences are not theoretical. WhatsApp us when you're ready to book.</p>{cta('en')}"""},
"ms":{"title":"5 Kesilapan Keselamatan Skylift Yang Menyebabkan Kemalangan","excerpt":"Lima kesilapan yang penyelia tapak ulang dengan sewa skylift — dan cara betulkan setiap satu sebelum sesiapa cedera.","meta_title":"5 Kesilapan Keselamatan Skylift — Skylift Malaysia","meta_desc":"Kesilapan keselamatan skylift di tapak Malaysia: abaikan outrigger, kelajuan angin, harness, had kapasiti, daya tampung tanah.","body":f"""{toc('ms',[('intro','Pengenalan'),('mistakes','Lima Kesilapan'),('checklist','Senarai Semak Sebelum Guna'),('cta','Sedia tempah?'),('conclusion','Penutup')])}<h2 id="intro">Pengenalan</h2><p>Kemalangan skylift di Malaysia jarang berpunca dari peralatan rosak. Ia berpunca dari pasukan tapak yang langkau langkah keselamatan asas kerana kerja dirasa rutin. Berikut lima kesilapan paling biasa — semak sebelum susun atur seterusnya.</p>{img(159306,'Penyelia tapak periksa skylift sebelum angkat')}<h2 id="mistakes">Lima Kesilapan</h2><h3>1. Abaikan pasangan outrigger</h3><p>"Lift kecil sahaja, tak perlu outrigger." Inilah punca #1 tergelincir. Setiap boom atas trak perlu keempat-empat outrigger dipanjangkan dan dikunci penuh, atas tanah keras, sebelum bakul tinggalkan kedudukan asal.</p><h3>2. Abaikan kelajuan angin</h3><p>Di atas 12.5 m/s (kira-kira 28 mph), boom lift kena diturunkan. Ramai penyelia tak periksa. Anemometer poket harga RM80 — beli satu.</p><h3>3. Tiada anchor harness dalam bakul</h3><p>Harness disangkut ke anchor dalam bakul, bukan ke struktur luar. Kalau bakul jatuh, anchor luar tukar pekerja jadi bandul.</p><h3>4. Lebih kapasiti</h3><p>Kebanyakan skylift had 230 kg. Dua pekerja + alatan + segulung kabel boleh capai had cepat. Baca pelekat kapasiti sebelum naik.</p><h3>5. Tanah lembut tanpa pad</h3<p>Outrigger tenggelam dalam aspal hari panas dan dalam tanah basah selepas hujan. Guna pad keluli atau kayu keras di bawah setiap kaki bila tanah bukan konkrit bertetulang.</p><h2 id="checklist">Senarai Semak Sebelum Guna</h2><blockquote>Outrigger · Angin · Harness · Kapasiti · Tanah · Sijil operator · Kawalan turun kecemasan · Tahap minyak · Tekanan tayar · Permit tapak</blockquote><p>Jalankan senarai ini setiap pagi, tiada pengecualian. Operator kami buat sebelum setiap tempahan — penyelia anda juga patut sahkan.</p><h2 id="cta">Sedia Tempah?</h2><p>Setiap sewa Skylift Malaysia termasuk operator bertauliah CIDB yang jalankan senarai semak bersama penyelia. {home_link('ms','Lihat fleet kami')} atau berbual:</p>{cta('ms')}<h2 id="conclusion">Penutup</h2><p>Keselamatan bukan kertas kerja — ia lima semakan yang ambil 90 saat. Langkau dan akibatnya bukan teori. WhatsApp kami bila sedia tempah.</p>{cta('ms')}"""},
"zh":{"title":"5 个导致工地事故的高空车安全错误","excerpt":"工地督导在高空车租用上反复犯的五个错误 — 以及在有人受伤前如何修正每一个。","meta_title":"5 个高空车安全错误 — Skylift Malaysia","meta_desc":"马来西亚工地反复出现的高空车安全错误:忽略支腿、风速、安全带挂点、载重限制、地面承重。","body":f"""{toc('zh',[('intro','简介'),('mistakes','五大错误'),('checklist','使用前检查清单'),('cta','准备预订?'),('conclusion','总结')])}<h2 id="intro">简介</h2><p>马来西亚的高空车事故很少由设备故障造成,而是由工地团队跳过基本安全步骤所致 — 因为工作感觉例行公事。以下是五个最常见错误 — 在下次部署前查阅。</p>{img(159306,'督导员在升起前检查高空车')}<h2 id="mistakes">五大错误</h2><h3>1. 跳过支腿展开</h3><p>"只是小升降机,不需要支腿。"这是翻车的第一原因。每台卡车装载式臂式车都需要四条支腿全部伸展锁紧、置于坚实地面后,再让平台离开支架。</p><h3>2. 忽略风速</h3><p>超过 12.5 m/s(约 28 mph)时,臂式车必须降下。许多督导甚至不检查。便携式风速仪只需 RM80 — 买一个吧。</p><h3>3. 平台内无安全带挂点</h3><p>安全带应扣在平台内的挂点,绝不能挂到外部结构上。若平台坠落,外部挂点会让工人变成钟摆。</p><h3>4. 超载</h3><p>大多数高空车上限 230 公斤。两个工人 + 工具 + 一卷电缆很快达到上限。上车前读载重贴纸。</p><h3>5. 软土地面无垫板</h3><p>支腿在炎热天气下会陷入沥青,在雨后会陷入湿土。地面非钢筋混凝土时,必须在每条腿下使用钢板或硬木垫板。</p><h2 id="checklist">使用前检查清单</h2><blockquote>支腿 · 风 · 安全带 · 载重 · 地面 · 操作员证 · 紧急下降控制 · 燃油 · 胎压 · 工地许可证</blockquote><p>每天早上跑这个清单,无例外。我们的操作员每次预订前都会做 — 您的督导也该签核。</p><h2 id="cta">准备预订?</h2><p>每次 Skylift Malaysia 租用都包含 CIDB 持证操作员,他会与您的督导一起跑安全清单。{home_link('zh','查看我们的车队')} 或咨询:</p>{cta('zh')}<h2 id="conclusion">总结</h2><p>安全不是文书工作 — 是五次只需 90 秒的检查。跳过的后果不是理论。准备好预订时 WhatsApp 我们。</p>{cta('zh')}"""}}

# ===== Article 4 — Spider lift vs boom =====
A4 = {"slug":"spider-lift-vs-boom-lift-which-one-do-you-need","cover":PEXELS(257700),
"en":{"title":"Spider Lift vs Boom Lift — Which One Do You Need?","excerpt":"Spider lift or boom lift? The simple decision tree based on access width, ground type, and reach height for Malaysian sites.","meta_title":"Spider Lift vs Boom Lift — Skylift Malaysia","meta_desc":"Spider lift vs boom lift comparison: access width, ground type, reach, indoor vs outdoor, costs. Pick the right unit for your job.","body":f"""{toc('en',[('intro','Introduction'),('compare','Quick Compare'),('decision','Decision Tree'),('cta','Ready to book?'),('conclusion','Conclusion')])}<h2 id="intro">Introduction</h2><p>Most contractors default to a truck-mounted boom because that's what they've always rented. But for indoor work, narrow access, or sensitive flooring, the spider lift wins on every count. Here's how to decide.</p>{img(1216597,'Spider lift navigating narrow indoor access')}<h2 id="compare">Quick Compare</h2><h3>Spider Skylift (18m reach)</h3><p>Tracked chassis, 90 cm wide, fits through standard doors. Outriggers self-deploy on uneven ground. RM850/day with operator. Best for atriums, malls, factories with concrete floors.</p><h3>20m Truck-Mounted Boom</h3><p>Drives at full road speed, deploys from the truck bed in 5 minutes. RM500 half-day / RM620 full. Best for shopfront signage, AC service, outdoor reach work in {loc_link('en','kuala-lumpur','Kuala Lumpur')}.</p><h2 id="decision">Decision Tree</h2><blockquote>Indoor or sensitive floor? → Spider. Outdoor with road access? → Boom. Indoor + height over 18m? → Custom solution, call us.</blockquote><h3>Width</h3><p>Spider fits through 90cm doorways. Boom needs 3m+ access for the truck.</p><h3>Ground bearing</h3><p>Spider distributes weight via 4 outriggers and tracks. Boom concentrates weight on outrigger pads. Marble or polished concrete floors? Spider only.</p><h3>Reach</h3><p>Spider tops at 18m working height. Boom comes in 9, 20, 24, 32m versions. If you need over 18m reach, you need a boom.</p><h2 id="cta">Ready to Book?</h2><p>Tell us the access width and the height — we'll send the right unit. {home_link('en','See all our units')}:</p>{cta('en')}<h2 id="conclusion">Conclusion</h2><p>Don't default to a boom because it's familiar. The spider lift exists for a reason — indoor reach work that booms can't do safely. WhatsApp us with site photos and we'll recommend the unit.</p>{cta('en')}"""},
"ms":{"title":"Spider Lift vs Boom Lift — Mana Satu Yang Anda Perlu?","excerpt":"Spider lift atau boom lift? Pokok keputusan ringkas berdasarkan lebar akses, jenis tanah, dan ketinggian capaian untuk tapak Malaysia.","meta_title":"Spider Lift vs Boom Lift — Skylift Malaysia","meta_desc":"Bandingan spider lift dan boom lift: lebar akses, jenis tanah, capaian, dalam vs luar bangunan, kos. Pilih unit yang betul untuk kerja anda.","body":f"""{toc('ms',[('intro','Pengenalan'),('compare','Bandingan Pantas'),('decision','Pokok Keputusan'),('cta','Sedia tempah?'),('conclusion','Penutup')])}<h2 id="intro">Pengenalan</h2><p>Ramai kontraktor pilih boom atas trak sebab itulah yang mereka selalu sewa. Tetapi untuk kerja dalam bangunan, akses sempit, atau lantai sensitif, spider lift menang setiap kali. Berikut cara buat keputusan.</p>{img(1216597,'Spider lift di akses sempit dalam bangunan')}<h2 id="compare">Bandingan Pantas</h2><h3>Spider Skylift (capaian 18m)</h3><p>Chassis trek, lebar 90 cm, muat pintu standard. Outrigger pasang sendiri di tanah tak rata. RM850/hari dengan operator. Terbaik untuk atrium, pasaraya, kilang berlantai konkrit.</p><h3>Boom 20m Atas Trak</h3><p>Memandu pada kelajuan jalan, susun atur dari katil trak dalam 5 minit. RM500 separuh / RM620 penuh. Terbaik untuk papan kedai, servis aircond, kerja luar di {loc_link('ms','kuala-lumpur','Kuala Lumpur')}.</p><h2 id="decision">Pokok Keputusan</h2><blockquote>Dalam bangunan atau lantai sensitif? → Spider. Luar dengan akses jalan? → Boom. Dalam + tinggi atas 18m? → Penyelesaian khas, hubungi kami.</blockquote><h3>Lebar</h3><p>Spider muat pintu 90cm. Boom perlu akses 3m+ untuk trak.</p><h3>Daya tampung tanah</h3><p>Spider agih berat melalui 4 outrigger dan trek. Boom pusatkan berat pada pad outrigger. Lantai marmar atau konkrit licin? Spider sahaja.</p><h3>Capaian</h3><p>Spider had 18m ketinggian kerja. Boom ada versi 9, 20, 24, 32m. Kalau perlu lebih 18m, anda perlu boom.</p><h2 id="cta">Sedia Tempah?</h2><p>Beritahu kami lebar akses dan ketinggian — kami hantar unit yang betul. {home_link('ms','Lihat semua unit kami')}:</p>{cta('ms')}<h2 id="conclusion">Penutup</h2><p>Jangan pilih boom sebab dah biasa. Spider lift wujud atas sebab — kerja capaian dalam bangunan yang boom tak boleh buat dengan selamat. WhatsApp kami dengan gambar tapak dan kami akan cadang unit.</p>{cta('ms')}"""},
"zh":{"title":"蜘蛛车 vs 臂式车 — 您需要哪一种?","excerpt":"蜘蛛车还是臂式车?基于通道宽度、地面类型和作业高度的简单决策树,适合马来西亚工地。","meta_title":"蜘蛛车 vs 臂式车 — Skylift Malaysia","meta_desc":"蜘蛛车和臂式车比较:通道宽度、地面类型、伸展、室内对室外、成本。为您的工程选对机型。","body":f"""{toc('zh',[('intro','简介'),('compare','快速对比'),('decision','决策树'),('cta','准备预订?'),('conclusion','总结')])}<h2 id="intro">简介</h2><p>大多数承包商默认选卡车臂式机,因为他们一直租这个。但对于室内工作、狭窄通道或敏感地板,蜘蛛车在每个方面都胜出。以下是决策方法。</p>{img(1216597,'蜘蛛车在室内狭窄通道')}<h2 id="compare">快速对比</h2><h3>蜘蛛高空车(18m 伸展)</h3><p>履带底盘,90 cm 宽,可通过标准门。支腿在不平地面自动展开。RM850/天含操作员。最适合中庭、商场、混凝土地板工厂。</p><h3>20m 卡车装载臂式车</h3><p>正常公路速度行驶,5 分钟内从车斗展开。RM500 半天 / RM620 全天。最适合 {loc_link('zh','kuala-lumpur','吉隆坡')} 的店面招牌、空调维修、室外伸展作业。</p><h2 id="decision">决策树</h2><blockquote>室内或敏感地板?→ 蜘蛛车。室外有道路通道?→ 臂式车。室内 + 高度超过 18m?→ 定制方案,联系我们。</blockquote><h3>宽度</h3><p>蜘蛛车可通过 90cm 门。臂式车的卡车需要 3m+ 通道。</p><h3>地面承重</h3><p>蜘蛛车通过 4 条支腿和履带分散重量。臂式车将重量集中在支腿垫板。大理石或抛光混凝土地板?仅蜘蛛车。</p><h3>伸展</h3><p>蜘蛛车工作高度上限 18m。臂式车有 9、20、24、32m 版本。需要超过 18m,就需要臂式车。</p><h2 id="cta">准备预订?</h2><p>告诉我们通道宽度和高度 — 我们派对的机型。{home_link('zh','查看我们所有机型')}:</p>{cta('zh')}<h2 id="conclusion">总结</h2><p>不要因为熟悉就默认选臂式车。蜘蛛车的存在是有原因的 — 臂式车无法安全完成的室内伸展工作。WhatsApp 我们工地照片,我们会推荐机型。</p>{cta('zh')}"""}}

# ===== Article 5 — CIDB MOSHA compliance =====
A5 = {"slug":"cidb-mosha-compliance-checklist-for-skylift-rental-malaysia","cover":PEXELS(1108572),
"en":{"title":"CIDB & MOSHA Compliance Checklist for Skylift Rental in Malaysia","excerpt":"What CIDB Green Card and MOSHA training mean for skylift work, and the documentation your site supervisor must verify before lifting.","meta_title":"CIDB MOSHA Compliance for Skylift Rental — Skylift Malaysia","meta_desc":"CIDB Green Card and MOSHA Mobile Elevating Work Platform training requirements for skylift operators in Malaysia. Site supervisor checklist.","body":f"""{toc('en',[('intro','Introduction'),('cidb','CIDB Green Card'),('mosha','MOSHA MEWP Training'),('docs','Documents to Check'),('cta','Ready to book?'),('conclusion','Conclusion')])}<h2 id="intro">Introduction</h2><p>If a skylift operator turns up at your site without a CIDB Green Card and MOSHA MEWP certification, you have two problems: a regulatory liability and an insurance gap. This checklist walks site supervisors through what to verify before any lift starts.</p>{img(162539,'Construction site supervisor checking compliance papers')}<h2 id="cidb">CIDB Green Card</h2><p>The CIDB Green Card is mandatory for all construction-site personnel under Section 33 of the CIDB Act 1994. It expires every 3 years. Operators arriving without a current card cannot legally enter your site.</p><p>What to check: photo matches the operator, expiry date is in the future, "Operator MEWP" or similar trade is listed.</p><h2 id="mosha">MOSHA MEWP Training</h2><p>MOSHA (Malaysian Occupational Safety & Health Association) runs the Mobile Elevating Work Platform course. It's the industry-recognised qualification for boom and scissor lift operation.</p><p>The course covers safety inspection, harness use, wind limits, and emergency lower procedures. Certificate is valid 3 years.</p><h2 id="docs">Documents to Check On Arrival</h2><blockquote>1. CIDB Green Card · 2. MOSHA MEWP cert · 3. Insurance cover note · 4. Equipment registration · 5. Site-specific risk assessment</blockquote><p>Skylift Malaysia operators carry all five. {home_link('en','See our fleet')}.</p><h2 id="cta">Ready to Book?</h2><p>Every booking ships with all documents pre-checked. Want to verify before delivery? WhatsApp us:</p>{cta('en')}<h2 id="conclusion">Conclusion</h2><p>Compliance isn't optional. The wrong operator on the wrong site can void your project insurance and trigger DOSH stop-work orders. Use a rental partner that handles this paperwork for you.</p>{cta('en')}"""},
"ms":{"title":"Senarai Semak Pematuhan CIDB & MOSHA untuk Sewa Skylift di Malaysia","excerpt":"Apa makna Kad Hijau CIDB dan latihan MOSHA untuk kerja skylift, dan dokumen yang penyelia tapak perlu sahkan sebelum mula angkat.","meta_title":"Pematuhan CIDB MOSHA untuk Sewa Skylift — Skylift Malaysia","meta_desc":"Keperluan Kad Hijau CIDB dan latihan MEWP MOSHA untuk operator skylift di Malaysia. Senarai semak penyelia tapak.","body":f"""{toc('ms',[('intro','Pengenalan'),('cidb','Kad Hijau CIDB'),('mosha','Latihan MEWP MOSHA'),('docs','Dokumen Untuk Disemak'),('cta','Sedia tempah?'),('conclusion','Penutup')])}<h2 id="intro">Pengenalan</h2><p>Kalau operator skylift sampai di tapak tanpa Kad Hijau CIDB dan sijil MEWP MOSHA, anda hadapi dua masalah: liabiliti pengawal selia dan jurang insurans. Senarai semak ini bawa penyelia tapak melalui apa yang perlu disahkan sebelum angkat.</p>{img(162539,'Penyelia tapak periksa dokumen pematuhan')}<h2 id="cidb">Kad Hijau CIDB</h2><p>Kad Hijau CIDB wajib bagi semua kakitangan tapak pembinaan di bawah Seksyen 33 Akta CIDB 1994. Tamat tempoh setiap 3 tahun. Operator yang sampai tanpa kad semasa tidak dibenarkan masuk tapak secara sah.</p><p>Apa nak semak: gambar padan dengan operator, tarikh tamat masih hadapan, tred "Operator MEWP" atau sebagainya tersenarai.</p><h2 id="mosha">Latihan MEWP MOSHA</h2><p>MOSHA (Persatuan Keselamatan & Kesihatan Pekerjaan Malaysia) jalankan kursus Platform Kerja Boleh Naik Bergerak. Inilah kelayakan rasmi industri untuk operasi boom dan scissor lift.</p><p>Kursus liputi pemeriksaan keselamatan, penggunaan harness, had angin, prosedur turun kecemasan. Sijil sah 3 tahun.</p><h2 id="docs">Dokumen Disemak Bila Sampai</h2><blockquote>1. Kad Hijau CIDB · 2. Sijil MEWP MOSHA · 3. Nota insurans · 4. Pendaftaran peralatan · 5. Penilaian risiko khusus tapak</blockquote><p>Operator Skylift Malaysia bawa kelima-lima. {home_link('ms','Lihat fleet kami')}.</p><h2 id="cta">Sedia Tempah?</h2><p>Setiap tempahan datang dengan semua dokumen dah disemak. Mahu sahkan sebelum penghantaran? WhatsApp kami:</p>{cta('ms')}<h2 id="conclusion">Penutup</h2><p>Pematuhan bukan pilihan. Operator salah di tapak salah boleh batalkan insurans projek dan cetus arahan henti kerja DOSH. Guna rakan kongsi sewa yang uruskan kertas kerja untuk anda.</p>{cta('ms')}"""},
"zh":{"title":"马来西亚高空车租用 CIDB 与 MOSHA 合规清单","excerpt":"CIDB 绿卡和 MOSHA 培训对高空车工作意味着什么,以及工地督导在升起前必须核实的文件。","meta_title":"高空车租用 CIDB MOSHA 合规 — Skylift Malaysia","meta_desc":"马来西亚高空车操作员的 CIDB 绿卡和 MOSHA 移动升降工作平台培训要求。工地督导清单。","body":f"""{toc('zh',[('intro','简介'),('cidb','CIDB 绿卡'),('mosha','MOSHA MEWP 培训'),('docs','应核实文件'),('cta','准备预订?'),('conclusion','总结')])}<h2 id="intro">简介</h2><p>如果高空车操作员到达工地却没有 CIDB 绿卡和 MOSHA MEWP 证书,您面临两个问题:监管责任和保险漏洞。本清单引导工地督导在任何升降开始前核实哪些事项。</p>{img(162539,'工地督导员检查合规文件')}<h2 id="cidb">CIDB 绿卡</h2><p>根据 1994 年 CIDB 法案第 33 条,所有建筑工地人员强制持有 CIDB 绿卡。每 3 年到期。无当前绿卡的操作员不能合法进入您的工地。</p><p>核实事项:照片与操作员相符、到期日尚在未来、列出"MEWP 操作员"或类似工种。</p><h2 id="mosha">MOSHA MEWP 培训</h2><p>MOSHA(马来西亚职业安全与健康协会)开设移动升降工作平台课程。这是臂式和剪刀式升降机操作的行业认可资格。</p><p>课程涵盖安全检查、安全带使用、风速限制、紧急下降程序。证书有效期 3 年。</p><h2 id="docs">到场后核实文件</h2><blockquote>1. CIDB 绿卡 · 2. MOSHA MEWP 证书 · 3. 保险通知书 · 4. 设备注册 · 5. 工地特定风险评估</blockquote><p>Skylift Malaysia 操作员携带全部五项。{home_link('zh','查看我们的车队')}.</p><h2 id="cta">准备预订?</h2><p>每次预订都附预先核实的所有文件。想在送达前核实?WhatsApp 我们:</p>{cta('zh')}<h2 id="conclusion">总结</h2><p>合规不是可选的。错的操作员在错的工地可能导致项目保险失效并触发 DOSH 停工令。选用为您处理这些文书的租用伙伴。</p>{cta('zh')}"""}}

# ===== Article 6 — Indoor ceiling work =====
A6 = {"slug":"indoor-ceiling-work-when-spider-skylift-beats-scaffolding","cover":PEXELS(1153213),
"en":{"title":"Indoor Ceiling Work: When a Spider Skylift Beats Scaffolding","excerpt":"For ceiling repaints, atrium glazing, and HVAC duct work, the spider skylift saves a full day per cycle vs scaffolding.","meta_title":"Spider Skylift vs Scaffolding for Ceiling Work — Skylift Malaysia","meta_desc":"When does a spider skylift beat scaffolding for indoor ceiling work? Cost, time, floor protection, and reach considerations.","body":f"""{toc('en',[('intro','Introduction'),('time','Time Comparison'),('cost','True Cost'),('cta','Ready to book?'),('cases','Best Use Cases'),('conclusion','Conclusion')])}<h2 id="intro">Introduction</h2><p>Scaffolding is the default for indoor ceiling work because crews are familiar with it. But for one-off jobs under 18m height, a spider skylift wins on time, cost, and floor protection. Here's the breakdown.</p>{img(1216544,'Spider skylift positioned for atrium ceiling work')}<h2 id="time">Time Comparison</h2><h3>Scaffolding</h3><p>Erection: 4–6 hours. Inspection sign-off: 1 hour. Take-down: 3–4 hours. Total dead-time: ~8–11 hours per cycle. Multiplied across multiple work zones, you lose days.</p><h3>Spider Skylift</h3><p>Driven into position in minutes. Outriggers self-deploy on uneven floors. Crew climbs into basket, lifts, works, lowers, drives to next position. Total dead-time: ~10 minutes per relocation.</p><h2 id="cost">True Cost</h2><blockquote>Scaffolding (10m × 5 zones): ~RM2,800 + 8 man-hours of erection labour. Spider skylift (1 day, 5 zones): RM850 with operator. Net saving: ~RM1,950 + a full day of project schedule.</blockquote><p>The spider lift is also faster to repaint around because there's no scaffold to mask off and no scaffolders blocking the work.</p><h2 id="cta">Ready to Book?</h2><p>{home_link('en','See our spider lift unit')} or send site photos and we'll confirm fit:</p>{cta('en')}<h2 id="cases">Best Use Cases</h2><h3>Atrium glazing</h3><p>Skylight cleaning, glass-pane replacement in shopping mall atriums.</p><h3>Mall ceiling repaint</h3><p>Quick mobilisation between shopfronts after closing hours.</p><h3>Factory HVAC</h3><p>Duct cleaning and damper repair in warehouse high-bays.</p><h2 id="conclusion">Conclusion</h2><p>If your job is under 18m and the floor allows tracked machinery, the spider lift saves you a day. WhatsApp us with site photos and we'll quote a fixed daily rate.</p>{cta('en')}"""},
"ms":{"title":"Kerja Siling Dalam Bangunan: Bila Spider Skylift Lebih Baik Daripada Scaffolding","excerpt":"Untuk cat semula siling, glazing atrium, dan kerja ducting HVAC, spider skylift jimatkan satu hari penuh setiap kitaran berbanding scaffolding.","meta_title":"Spider Skylift vs Scaffolding untuk Kerja Siling — Skylift Malaysia","meta_desc":"Bila spider skylift lebih baik daripada scaffolding untuk kerja siling dalam bangunan? Pertimbangan kos, masa, perlindungan lantai, dan capaian.","body":f"""{toc('ms',[('intro','Pengenalan'),('time','Bandingan Masa'),('cost','Kos Sebenar'),('cta','Sedia tempah?'),('cases','Kes Penggunaan Terbaik'),('conclusion','Penutup')])}<h2 id="intro">Pengenalan</h2><p>Scaffolding ialah pilihan asas untuk kerja siling dalam bangunan sebab krew sudah biasa. Tetapi untuk kerja sekali-sekala di bawah 18m, spider skylift menang dari segi masa, kos, dan perlindungan lantai. Berikut perinciannya.</p>{img(1216544,'Spider skylift dipasang untuk kerja siling atrium')}<h2 id="time">Bandingan Masa</h2><h3>Scaffolding</h3><p>Pasangan: 4–6 jam. Pengesahan pemeriksaan: 1 jam. Pembongkaran: 3–4 jam. Jumlah masa terbuang: ~8–11 jam setiap kitaran. Didarab merentasi banyak zon kerja, anda hilang berhari-hari.</p><h3>Spider Skylift</h3><p>Dipandu ke kedudukan dalam beberapa minit. Outrigger pasang sendiri di lantai tak rata. Krew naik bakul, angkat, kerja, turun, pandu ke kedudukan seterusnya. Jumlah masa terbuang: ~10 minit setiap pemindahan.</p><h2 id="cost">Kos Sebenar</h2><blockquote>Scaffolding (10m × 5 zon): ~RM2,800 + 8 jam-lelaki tenaga kerja pasang. Spider skylift (1 hari, 5 zon): RM850 dengan operator. Penjimatan bersih: ~RM1,950 + satu hari penuh jadual projek.</blockquote><p>Spider lift juga lebih cepat untuk cat sekeliling sebab tiada scaffold untuk dilindungi dan tiada pekerja scaffold yang menghalang kerja.</p><h2 id="cta">Sedia Tempah?</h2><p>{home_link('ms','Lihat unit spider lift kami')} atau hantar gambar tapak dan kami akan sahkan kesesuaian:</p>{cta('ms')}<h2 id="cases">Kes Penggunaan Terbaik</h2><h3>Glazing atrium</h3><p>Cuci skylight, ganti panel kaca di atrium pasaraya.</p><h3>Cat semula siling pasaraya</h3><p>Mobilisasi pantas antara papan kedai selepas waktu tutup.</p><h3>HVAC kilang</h3><p>Cuci ducting dan baiki damper di gudang bumbung tinggi.</p><h2 id="conclusion">Penutup</h2><p>Kalau kerja anda di bawah 18m dan lantai benarkan jentera trek, spider lift jimat anda satu hari. WhatsApp kami dengan gambar tapak dan kami akan beri kadar harian tetap.</p>{cta('ms')}"""},
"zh":{"title":"室内天花板工作:何时蜘蛛车胜过脚手架","excerpt":"对于天花板重绘、中庭玻璃、HVAC 风管工作,蜘蛛高空车比脚手架每周期节省一整天。","meta_title":"蜘蛛车 vs 脚手架天花板工作 — Skylift Malaysia","meta_desc":"蜘蛛高空车何时在室内天花板工作中胜过脚手架?成本、时间、地板保护与伸展考量。","body":f"""{toc('zh',[('intro','简介'),('time','时间对比'),('cost','真实成本'),('cta','准备预订?'),('cases','最佳应用'),('conclusion','总结')])}<h2 id="intro">简介</h2><p>脚手架是室内天花板工作的默认选择,因为施工队熟悉它。但对于 18m 以下的一次性工程,蜘蛛车在时间、成本和地板保护上都胜出。以下是分析。</p>{img(1216544,'蜘蛛车定位用于中庭天花板工作')}<h2 id="time">时间对比</h2><h3>脚手架</h3><p>搭建:4–6 小时。检查签核:1 小时。拆除:3–4 小时。每周期总耗时:~8–11 小时。乘以多个工作区,损失数天。</p><h3>蜘蛛高空车</h3><p>几分钟内驶到位置。支腿在不平地面自动展开。施工队进入平台,升起,工作,降下,开到下一个位置。每次重定位总耗时:~10 分钟。</p><h2 id="cost">真实成本</h2><blockquote>脚手架(10m × 5 区):~RM2,800 + 8 人时搭建劳力。蜘蛛车(1 天,5 区):RM850 含操作员。净节省:~RM1,950 + 项目进度一整天。</blockquote><p>蜘蛛车在油漆作业时也更快,因为没有脚手架要遮挡,没有搭架工人挡路。</p><h2 id="cta">准备预订?</h2><p>{home_link('zh','查看我们的蜘蛛车机型')} 或发送工地照片我们确认是否合适:</p>{cta('zh')}<h2 id="cases">最佳应用</h2><h3>中庭玻璃</h3><p>商场中庭天窗清洗、玻璃面板更换。</p><h3>商场天花板重绘</h3><p>营业时间结束后在店面之间快速移动。</p><h3>工厂 HVAC</h3><p>仓库高架内的风管清洗和阻尼器修复。</p><h2 id="conclusion">总结</h2><p>如果工程在 18m 以下且地板允许履带式机械,蜘蛛车为您节省一天。WhatsApp 我们工地照片,我们会报固定日租。</p>{cta('zh')}"""}}

# ===== Article 7 — Same-day delivery =====
A7 = {"slug":"same-day-skylift-delivery-how-it-works-kl-selangor","cover":PEXELS(1216597),
"en":{"title":"Same-Day Skylift Delivery: How It Works in KL & Selangor","excerpt":"How Skylift Malaysia delivers a 20m unit to your KL or Selangor site within 2 hours of WhatsApp confirmation.","meta_title":"Same-Day Skylift Delivery KL Selangor — Skylift Malaysia","meta_desc":"Same-day skylift delivery across KL and Selangor. WhatsApp at 9am, unit on site by 11am — here's how the dispatch process works.","body":f"""{toc('en',[('intro','Introduction'),('process','The Delivery Process'),('zones','Coverage Zones'),('cta','Ready to book?'),('limits','When Same-Day Is Not Possible'),('conclusion','Conclusion')])}<h2 id="intro">Introduction</h2><p>You can have a 20m skylift on your site within 2 hours of WhatsApp confirmation, anywhere in KL or Selangor. Here's how it works behind the scenes — and the few cases where same-day isn't possible.</p>{img(1216544,'Skylift truck arriving at site within hours')}<h2 id="process">The Delivery Process</h2><h3>Step 1: WhatsApp confirmation (5 min)</h3><p>Send job address, height needed, and start time. We confirm price, operator, and ETA.</p><h3>Step 2: Operator dispatch (15 min)</h3><p>Nearest available CIDB-certified operator gets the job. Truck is fuelled and pre-checked at our depot.</p><h3>Step 3: Drive to site (45–90 min)</h3><p>Depending on traffic and your location relative to {loc_link('en','kuala-lumpur','our KL')} or {loc_link('en','shah-alam','Shah Alam')} depots.</p><h3>Step 4: Site setup (10 min)</h3><p>Outriggers deployed, harness check, your supervisor signs the daily-use log.</p><h2 id="zones">Coverage Zones</h2><blockquote>Tier 1 (under 90 min): KL, PJ, Shah Alam, Subang, Puchong, Cheras, Ampang. Tier 2 (under 2.5 hr): Klang, Kajang, Cyberjaya, Sepang. Outside Klang Valley: book a day ahead.</blockquote><h2 id="cta">Ready to Book?</h2><p>WhatsApp now — we'll quote and confirm ETA within 5 minutes.</p>{cta('en')}<h2 id="limits">When Same-Day Isn't Possible</h2><p>Saturday afternoon (operators booked solid). Heavy rain warnings (delivery paused for safety). Out-of-state jobs (Penang, Johor, etc.). For these, book at least 24 hours ahead.</p><h2 id="conclusion">Conclusion</h2><p>Same-day delivery is the standard, not the exception. WhatsApp us with the address and we'll dispatch immediately.</p>{cta('en')}"""},
"ms":{"title":"Penghantaran Skylift Hari Sama: Bagaimana Ia Berjalan di KL & Selangor","excerpt":"Bagaimana Skylift Malaysia hantar unit 20m ke tapak anda di KL atau Selangor dalam 2 jam selepas pengesahan WhatsApp.","meta_title":"Penghantaran Skylift Hari Sama KL Selangor — Skylift Malaysia","meta_desc":"Penghantaran skylift hari sama di seluruh KL dan Selangor. WhatsApp pukul 9 pagi, unit di tapak menjelang 11 pagi — proses dispatch.","body":f"""{toc('ms',[('intro','Pengenalan'),('process','Proses Penghantaran'),('zones','Zon Liputan'),('cta','Sedia tempah?'),('limits','Bila Hari Sama Tak Boleh'),('conclusion','Penutup')])}<h2 id="intro">Pengenalan</h2><p>Anda boleh dapat skylift 20m di tapak dalam 2 jam dari pengesahan WhatsApp, di mana sahaja dalam KL atau Selangor. Berikut bagaimana ia berjalan di belakang tabir — dan beberapa kes hari sama tak boleh.</p>{img(1216544,'Skylift sampai di tapak dalam beberapa jam')}<h2 id="process">Proses Penghantaran</h2><h3>Langkah 1: Pengesahan WhatsApp (5 minit)</h3><p>Hantar alamat tapak, ketinggian perlu, dan masa mula. Kami sahkan harga, operator, dan ETA.</p><h3>Langkah 2: Dispatch operator (15 minit)</h3<p>Operator bertauliah CIDB terdekat dapat kerja. Trak diisi minyak dan diperiksa di depot kami.</p><h3>Langkah 3: Pandu ke tapak (45–90 minit)</h3><p>Bergantung trafik dan lokasi anda berbanding depot {loc_link('ms','kuala-lumpur','KL')} atau {loc_link('ms','shah-alam','Shah Alam')}.</p><h3>Langkah 4: Susun atur tapak (10 minit)</h3><p>Outrigger dipasang, semakan harness, penyelia anda tanda log guna harian.</p><h2 id="zones">Zon Liputan</h2><blockquote>Tier 1 (bawah 90 minit): KL, PJ, Shah Alam, Subang, Puchong, Cheras, Ampang. Tier 2 (bawah 2.5 jam): Klang, Kajang, Cyberjaya, Sepang. Luar Lembah Klang: tempah sehari awal.</blockquote><h2 id="cta">Sedia Tempah?</h2><p>WhatsApp sekarang — kami sebut harga dan sahkan ETA dalam 5 minit.</p>{cta('ms')}<h2 id="limits">Bila Hari Sama Tak Boleh</h2><p>Petang Sabtu (operator penuh tempahan). Amaran hujan lebat (penghantaran dijeda untuk keselamatan). Kerja luar negeri (Pulau Pinang, Johor, dll). Untuk ini, tempah sekurang-kurangnya 24 jam awal.</p><h2 id="conclusion">Penutup</h2><p>Penghantaran hari sama ialah kebiasaan, bukan pengecualian. WhatsApp kami dengan alamat dan kami akan dispatch segera.</p>{cta('ms')}"""},
"zh":{"title":"当天高空车送达:KL 与雪兰莪如何运作","excerpt":"Skylift Malaysia 如何在 WhatsApp 确认后 2 小时内将 20m 机型送达您 KL 或雪兰莪的工地。","meta_title":"当天送达高空车 KL 雪兰莪 — Skylift Malaysia","meta_desc":"KL 和雪兰莪全境当天高空车送达。早 9 点 WhatsApp,11 点机器到工地 — 派遣流程解析。","body":f"""{toc('zh',[('intro','简介'),('process','送达流程'),('zones','覆盖区域'),('cta','准备预订?'),('limits','无法当天送达的情况'),('conclusion','总结')])}<h2 id="intro">简介</h2><p>您可以在 WhatsApp 确认后 2 小时内,在 KL 或雪兰莪任何位置获得 20m 高空车。以下是幕后运作,以及少数无法当天送达的情况。</p>{img(1216544,'高空车在数小时内抵达工地')}<h2 id="process">送达流程</h2><h3>第 1 步:WhatsApp 确认(5 分钟)</h3><p>发送工地地址、所需高度、开工时间。我们确认价格、操作员和 ETA。</p><h3>第 2 步:派遣操作员(15 分钟)</h3><p>最近的 CIDB 持证操作员接单。卡车在车场加油并预检。</p><h3>第 3 步:驶往工地(45–90 分钟)</h3><p>根据交通和您相对于 {loc_link('zh','kuala-lumpur','吉隆坡')} 或 {loc_link('zh','shah-alam','莎阿南')} 车场的位置。</p><h3>第 4 步:工地设置(10 分钟)</h3><p>展开支腿、安全带检查、您的督导签署日用记录。</p><h2 id="zones">覆盖区域</h2><blockquote>一级(90 分钟内):KL、PJ、莎阿南、梳邦、蒲种、蕉赖、安邦。二级(2.5 小时内):巴生、加影、赛城、雪邦。雪隆以外:提前一天预订。</blockquote><h2 id="cta">准备预订?</h2><p>立即 WhatsApp — 5 分钟内报价并确认 ETA。</p>{cta('zh')}<h2 id="limits">无法当天送达的情况</h2><p>周六下午(操作员全订满)。暴雨警报(为安全暂停送达)。外州工程(槟城、柔佛等)。这些情况请提前 24 小时预订。</p><h2 id="conclusion">总结</h2><p>当天送达是标准,而非例外。WhatsApp 我们地址,我们立即派遣。</p>{cta('zh')}"""}}

# ===== Article 8 — Top industries =====
A8 = {"slug":"top-7-industries-that-rent-skylifts-most-in-kl-selangor","cover":PEXELS(1216544),
"en":{"title":"Top 7 Industries That Rent Skylifts Most in KL & Selangor","excerpt":"Construction, telco, advertising, mall maintenance, factory upkeep, urban tree services, film production — these seven sectors keep our fleet busy.","meta_title":"Top 7 Industries Renting Skylifts KL Selangor — Skylift Malaysia","meta_desc":"Which industries rent skylifts most in KL and Selangor? Construction, telco, signage, mall maintenance, factory, tree services, film.","body":f"""{toc('en',[('intro','Introduction'),('list','The Seven Industries'),('cta','Ready to book?'),('conclusion','Conclusion')])}<h2 id="intro">Introduction</h2><p>If you've ever wondered who rents skylifts day in, day out across KL and Selangor — here are the seven industries that keep our fleet booked. Each section includes the typical unit they choose and a sample job.</p>{img(159306,'Skylift truck on busy KL job site')}<h2 id="list">The Seven Industries</h2><h3>1. Construction & contractors</h3><p>Most-frequent customer. Rental: 20m and 24m booms. Job: facade work, structural fitting, glazing on residential high-rise in {loc_link('en','petaling-jaya','Petaling Jaya')}.</p><h3>2. Telecommunications</h3><p>Fibre-optic stringing, antenna installation on rooftops. Unit: 24m. Often booked monthly during city-wide rollouts.</p><h3>3. Advertising & signage</h3><p>Shopfront LED signs, highway billboards. Unit: 20m for shopfronts, 32m for highway boards. Often half-day jobs.</p><h3>4. Shopping mall maintenance</h3><p>After-hours ceiling repair, lighting replacement, glazing cleaning. Unit: 9m or spider lift. Recurring monthly contracts common.</p><h3>5. Factory & warehouse upkeep</h3><p>HVAC duct service, roof inspection, sprinkler maintenance. Unit: 20m or 24m. Industrial estates in {loc_link('en','shah-alam','Shah Alam')} are our biggest cluster.</p><h3>6. Urban tree services</h3><p>Branch trimming along main roads under JKR contracts. Unit: 20m. Year-round work.</p><h3>7. Film & event production</h3><p>Camera rigs, lighting trusses for outdoor productions. Unit: 9m or 20m depending on shot. Short-term, premium-rate bookings.</p><h2 id="cta">Ready to Book?</h2><p>Whatever industry you're in, we have the right unit. {home_link('en','See our fleet')} or chat now:</p>{cta('en')}<h2 id="conclusion">Conclusion</h2><p>If your work needs reach, you're not alone. WhatsApp us — we'll match your job to the right unit and operator within 5 minutes.</p>{cta('en')}"""},
"ms":{"title":"7 Industri Teratas Yang Paling Banyak Sewa Skylift di KL & Selangor","excerpt":"Pembinaan, telco, iklan, penyelenggaraan pasaraya, kilang, perkhidmatan pokok bandar, produksi filem — tujuh sektor ini buat fleet kami sibuk.","meta_title":"7 Industri Sewa Skylift KL Selangor — Skylift Malaysia","meta_desc":"Industri mana yang paling banyak sewa skylift di KL dan Selangor? Pembinaan, telco, papan iklan, pasaraya, kilang, pokok, filem.","body":f"""{toc('ms',[('intro','Pengenalan'),('list','Tujuh Industri'),('cta','Sedia tempah?'),('conclusion','Penutup')])}<h2 id="intro">Pengenalan</h2><p>Kalau anda pernah tertanya siapa yang sewa skylift hari demi hari di seluruh KL dan Selangor — berikut tujuh industri yang buat fleet kami penuh tempahan. Setiap seksyen termasuk unit tipikal dan contoh kerja.</p>{img(159306,'Skylift di tapak kerja KL yang sibuk')}<h2 id="list">Tujuh Industri</h2><h3>1. Pembinaan & kontraktor</h3><p>Pelanggan paling kerap. Sewa: boom 20m dan 24m. Kerja: kerja fasad, pemasangan struktur, glazing di pangsapuri tinggi {loc_link('ms','petaling-jaya','Petaling Jaya')}.</p><h3>2. Telekomunikasi</h3><p>Pemasangan kabel fiber optik, antena bumbung. Unit: 24m. Selalu tempah bulanan semasa rollout bandar.</p><h3>3. Pengiklanan & papan tanda</h3><p>Papan LED kedai, papan iklan lebuhraya. Unit: 20m untuk kedai, 32m untuk papan lebuhraya. Selalu kerja separuh hari.</p><h3>4. Penyelenggaraan pasaraya</h3><p>Baiki siling waktu malam, ganti lampu, cuci glazing. Unit: 9m atau spider lift. Kontrak bulanan berulang biasa.</p><h3>5. Penjagaan kilang & gudang</h3><p>Servis ducting HVAC, pemeriksaan bumbung, penyelenggaraan sprinkler. Unit: 20m atau 24m. Kawasan perindustrian {loc_link('ms','shah-alam','Shah Alam')} kelompok terbesar kami.</p><h3>6. Perkhidmatan pokok bandar</h3><p>Pemangkasan dahan tepi jalan utama bawah kontrak JKR. Unit: 20m. Kerja sepanjang tahun.</p><h3>7. Produksi filem & acara</h3><p>Rigs kamera, truss lampu untuk produksi luar. Unit: 9m atau 20m bergantung shot. Tempahan jangka pendek, kadar premium.</p><h2 id="cta">Sedia Tempah?</h2><p>Apa pun industri anda, kami ada unit yang betul. {home_link('ms','Lihat fleet kami')} atau berbual sekarang:</p>{cta('ms')}<h2 id="conclusion">Penutup</h2><p>Kalau kerja anda perlukan capaian, anda tidak keseorangan. WhatsApp kami — kami padankan kerja dengan unit dan operator yang betul dalam 5 minit.</p>{cta('ms')}"""},
"zh":{"title":"KL 与雪兰莪最常租用高空车的 7 大行业","excerpt":"建筑、电信、广告、商场维护、工厂保养、城市树木服务、影视制作 — 这七大行业让我们车队忙不停。","meta_title":"7 大租用高空车行业 KL 雪兰莪 — Skylift Malaysia","meta_desc":"KL 和雪兰莪哪些行业最常租用高空车?建筑、电信、招牌、商场、工厂、树木、影视。","body":f"""{toc('zh',[('intro','简介'),('list','七大行业'),('cta','准备预订?'),('conclusion','总结')])}<h2 id="intro">简介</h2><p>如果您好奇 KL 和雪兰莪谁日复一日地租用高空车 — 这里是让我们车队订满的七大行业。每节包括典型机型和工程实例。</p>{img(159306,'KL 繁忙工地的高空车')}<h2 id="list">七大行业</h2><h3>1. 建筑与承包商</h3><p>最频繁的客户。租用:20m 和 24m 臂式机。工程:立面、结构装配、{loc_link('zh','petaling-jaya','八打灵再也')} 高层公寓玻璃。</p><h3>2. 电信</h3><p>光纤布线、屋顶天线安装。机型:24m。城市级铺设期间常按月预订。</p><h3>3. 广告与招牌</h3><p>店面 LED 招牌、高速公路广告牌。机型:店面 20m,高速 32m。常半天工作。</p><h3>4. 商场维护</h3><p>夜间天花板维修、灯具更换、玻璃清洁。机型:9m 或蜘蛛车。每月重复合约常见。</p><h3>5. 工厂与仓库保养</h3><p>HVAC 风管服务、屋顶检查、洒水器维护。机型:20m 或 24m。{loc_link('zh','shah-alam','莎阿南')} 工业区是我们最大集群。</p><h3>6. 城市树木服务</h3><p>JKR 合约下的主干道树枝修剪。机型:20m。全年工作。</p><h3>7. 影视与活动制作</h3><p>摄像机吊装、户外制作灯架。机型:9m 或 20m 视镜头而定。短期、高费率预订。</p><h2 id="cta">准备预订?</h2><p>无论您在哪个行业,我们都有合适的机型。{home_link('zh','查看我们的车队')} 或现在咨询:</p>{cta('zh')}<h2 id="conclusion">总结</h2><p>如果您的工作需要伸展,您并不孤单。WhatsApp 我们 — 5 分钟内为您匹配合适的机型和操作员。</p>{cta('zh')}"""}}

# ===== Article 9 — Operator certification =====
A9 = {"slug":"skylift-operator-certification-what-supervisors-must-verify","cover":PEXELS(162539),
"en":{"title":"Skylift Operator Certification: What Your Site Supervisor Must Verify","excerpt":"The exact certifications a skylift operator must hold and how to verify them in 60 seconds before any lift starts.","meta_title":"Skylift Operator Certification — Site Supervisor Guide","meta_desc":"What every site supervisor must verify on a skylift operator: CIDB Green Card, MOSHA MEWP, equipment registration, insurance.","body":f"""{toc('en',[('intro','Introduction'),('certs','Required Certifications'),('verify','60-Second Verification'),('cta','Ready to book?'),('conclusion','Conclusion')])}<h2 id="intro">Introduction</h2><p>The single biggest reason skylift bookings get delayed at the gate is missing or expired operator certs. Here's what your supervisor must check before lift-off.</p>{img(1108572,'Operator and supervisor reviewing certs on site')}<h2 id="certs">Required Certifications</h2><h3>CIDB Green Card (3-year cycle)</h3><p>Mandatory for all construction-site personnel. Photo, name, expiry, and trade must be readable.</p><h3>MOSHA MEWP Certificate (3-year cycle)</h3><p>Specifically for Mobile Elevating Work Platform — the formal qualification for boom lift operation.</p><h3>Equipment registration</h3><p>The skylift unit itself must have a current registration plate and recent inspection sticker.</p><h3>Insurance cover note</h3><p>Operator and equipment insurance must be in date for the booking period.</p><h2 id="verify">60-Second Verification</h2><blockquote>1. Match operator photo to ID. 2. Check expiry dates. 3. Verify trade lists "MEWP" or "Boom Lift". 4. Confirm equipment plate matches paperwork. 5. Sign daily-use log.</blockquote><p>Skylift Malaysia operators arrive with all four documents in a sealed wallet. {home_link('en','See our compliance policy')}.</p><h2 id="cta">Ready to Book?</h2><p>Every booking ships with verified docs. WhatsApp us:</p>{cta('en')}<h2 id="conclusion">Conclusion</h2><p>60 seconds of verification at the gate prevents 60 minutes of stop-work later. Make it a daily habit. Operators in {loc_link('en','kuala-lumpur','Kuala Lumpur')} jobs face the toughest scrutiny — be ready.</p>{cta('en')}"""},
"ms":{"title":"Sijil Operator Skylift: Apa Penyelia Tapak Wajib Sahkan","excerpt":"Sijil yang operator skylift mesti ada dan cara sahkan dalam 60 saat sebelum kerja angkat bermula.","meta_title":"Sijil Operator Skylift — Panduan Penyelia","meta_desc":"Apa setiap penyelia tapak mesti sahkan pada operator skylift: Kad Hijau CIDB, MOSHA MEWP, pendaftaran peralatan, insurans.","body":f"""{toc('ms',[('intro','Pengenalan'),('certs','Sijil Diperlukan'),('verify','Pengesahan 60 Saat'),('cta','Sedia tempah?'),('conclusion','Penutup')])}<h2 id="intro">Pengenalan</h2><p>Sebab tunggal terbesar tempahan skylift tertangguh di pintu pagar ialah sijil operator hilang atau tamat tempoh. Berikut apa penyelia anda mesti semak sebelum angkat.</p>{img(1108572,'Operator dan penyelia semak sijil di tapak')}<h2 id="certs">Sijil Diperlukan</h2><h3>Kad Hijau CIDB (kitaran 3 tahun)</h3><p>Wajib bagi semua kakitangan tapak pembinaan. Gambar, nama, tarikh tamat, dan tred mesti boleh dibaca.</p><h3>Sijil MEWP MOSHA (kitaran 3 tahun)</h3><p>Khusus untuk Platform Kerja Boleh Naik Bergerak — kelayakan rasmi operasi boom lift.</p><h3>Pendaftaran peralatan</h3><p>Unit skylift sendiri mesti ada plat pendaftaran semasa dan pelekat pemeriksaan terkini.</p><h3>Nota perlindungan insurans</h3><p>Insurans operator dan peralatan mesti masih sah untuk tempoh tempahan.</p><h2 id="verify">Pengesahan 60 Saat</h2><blockquote>1. Padan gambar operator dengan IC. 2. Semak tarikh tamat. 3. Sahkan tred senaraikan "MEWP" atau "Boom Lift". 4. Sahkan plat peralatan padan kertas kerja. 5. Tanda log guna harian.</blockquote><p>Operator Skylift Malaysia sampai dengan keempat-empat dokumen dalam dompet tertutup. {home_link('ms','Lihat polisi pematuhan kami')}.</p><h2 id="cta">Sedia Tempah?</h2><p>Setiap tempahan datang dengan dokumen disahkan. WhatsApp kami:</p>{cta('ms')}<h2 id="conclusion">Penutup</h2><p>60 saat pengesahan di pintu pagar elak 60 minit henti kerja kemudian. Jadikan tabiat harian. Operator di kerja {loc_link('ms','kuala-lumpur','Kuala Lumpur')} hadapi pengawasan paling ketat — bersedia.</p>{cta('ms')}"""},
"zh":{"title":"高空车操作员认证:工地督导必须核实什么","excerpt":"高空车操作员必须持有的确切证书,以及如何在升起前 60 秒内核实它们。","meta_title":"高空车操作员认证 — 督导指南","meta_desc":"每位工地督导必须核实的高空车操作员事项:CIDB 绿卡、MOSHA MEWP、设备注册、保险。","body":f"""{toc('zh',[('intro','简介'),('certs','所需证书'),('verify','60 秒核实'),('cta','准备预订?'),('conclusion','总结')])}<h2 id="intro">简介</h2><p>高空车预订在工地大门被延误的最大单一原因是缺失或过期的操作员证书。以下是您督导在升降前必须检查的内容。</p>{img(1108572,'操作员和督导在工地核实证书')}<h2 id="certs">所需证书</h2><h3>CIDB 绿卡(3 年一次)</h3><p>所有建筑工地人员强制。照片、姓名、到期日和工种必须可读。</p><h3>MOSHA MEWP 证书(3 年一次)</h3><p>特定于移动升降工作平台 — 臂式车操作的正式资格。</p><h3>设备注册</h3><p>高空车机型本身必须有当前注册牌照和近期检查贴纸。</p><h3>保险通知书</h3><p>操作员和设备保险必须在预订期内有效。</p><h2 id="verify">60 秒核实</h2><blockquote>1. 操作员照片对身份证。2. 检查到期日。3. 核实工种列出"MEWP"或"Boom Lift"。4. 确认设备牌照与文件相符。5. 签日用记录。</blockquote><p>Skylift Malaysia 操作员到场时四份文件都在密封文件夹中。{home_link('zh','查看我们的合规政策')}.</p><h2 id="cta">准备预订?</h2><p>每次预订都附核实过的文件。WhatsApp 我们:</p>{cta('zh')}<h2 id="conclusion">总结</h2><p>大门 60 秒核实可避免后续 60 分钟停工。让它成为日常习惯。{loc_link('zh','kuala-lumpur','吉隆坡')} 工程的操作员面对最严格审查 — 要做好准备。</p>{cta('zh')}"""}}

# ===== Article 10 — Renting vs buying =====
A10 = {"slug":"renting-vs-buying-a-skylift-cost-breakdown-for-sme-contractors","cover":PEXELS(159306),
"en":{"title":"Renting vs Buying a Skylift — A Cost Breakdown for SME Contractors","excerpt":"When does it make sense to buy a skylift instead of renting? The break-even maths for Malaysian SME contractors.","meta_title":"Rent or Buy a Skylift? Cost Breakdown — Skylift Malaysia","meta_desc":"Should an SME contractor in Malaysia rent or buy a skylift? Break-even analysis covering CAPEX, depreciation, maintenance, idle days.","body":f"""{toc('en',[('intro','Introduction'),('rent','Renting Maths'),('buy','Buying Maths'),('breakeven','Break-Even Point'),('cta','Ready to book?'),('conclusion','Conclusion')])}<h2 id="intro">Introduction</h2><p>You hit 5 skylift jobs in a month and start asking — should we just buy one? This is the maths every SME contractor should run before signing a finance lease.</p>{img(1238864,'Skylift truck parked at contractor yard')}<h2 id="rent">Renting Maths</h2><p>20m skylift rental: RM620/day full or RM500/day half. Rented 80 days a year (a heavy schedule for a single contractor): annual cost ≈ RM50,000. Operator, fuel, insurance, depreciation — all on us.</p><h2 id="buy">Buying Maths</h2><p>New 20m boom truck: RM450k–RM550k. Used (5 years): RM200k–RM280k. Add: <strong>insurance ~RM8k/yr · road tax + permits ~RM3k · operator salary ~RM3k/mo · maintenance ~RM10k/yr · depreciation ~RM45k/yr (year 1).</strong></p><p>Annual fixed cost ownership: ~RM110,000. To break-even on rental at RM620/day, you'd need 178 utilisation days — basically full-time work, every working week.</p><h2 id="breakeven">The Break-Even Reality</h2><blockquote>Below 100 days/year of skylift work → rent. 100–150 days/year → still rent (idle days kill ROI). Above 150 days/year sustained → consider purchase, ideally used unit + dedicated operator.</blockquote><p>Most SME contractors are in the 30–80 day range. Renting wins decisively at that volume. {home_link('en','Browse our fleet')} for current rental rates.</p><h2 id="cta">Ready to Book?</h2><p>Skip the CAPEX. WhatsApp us when you need a unit:</p>{cta('en')}<h2 id="conclusion">Conclusion</h2><p>Buy when utilisation is sustained above 150 days/year. Below that, rental is cheaper, more flexible, and shifts the maintenance + operator overhead to us. Most SMEs in {loc_link('en','shah-alam','Shah Alam')} and KL stay rental-only.</p>{cta('en')}"""},
"ms":{"title":"Sewa atau Beli Skylift — Pecahan Kos untuk Kontraktor SME","excerpt":"Bila masuk akal beli skylift dan bukan sewa? Matematik break-even untuk kontraktor SME Malaysia.","meta_title":"Sewa atau Beli Skylift? Pecahan Kos — Skylift Malaysia","meta_desc":"Sewa atau beli skylift di Malaysia? Analisis break-even meliputi CAPEX, susut nilai, penyelenggaraan, hari terbiar.","body":f"""{toc('ms',[('intro','Pengenalan'),('rent','Matematik Sewa'),('buy','Matematik Beli'),('breakeven','Titik Break-Even'),('cta','Sedia tempah?'),('conclusion','Penutup')])}<h2 id="intro">Pengenalan</h2><p>Anda capai 5 kerja skylift sebulan dan mula bertanya — patut kita beli satu? Inilah matematik yang setiap kontraktor SME patut buat sebelum tandatangan pajak.</p>{img(1238864,'Skylift di yard kontraktor')}<h2 id="rent">Matematik Sewa</h2><p>Sewa skylift 20m: RM620/hari penuh atau RM500/hari separuh. Disewa 80 hari setahun (jadual berat untuk seorang kontraktor): kos tahunan ≈ RM50,000. Operator, minyak, insurans, susut nilai — semua atas kami.</p><h2 id="buy">Matematik Beli</h2><p>Trak boom 20m baru: RM450k–RM550k. Terpakai (5 tahun): RM200k–RM280k. Tambah: <strong>insurans ~RM8k/tahun · cukai jalan + permit ~RM3k · gaji operator ~RM3k/bulan · penyelenggaraan ~RM10k/tahun · susut nilai ~RM45k/tahun (tahun 1).</strong></p><p>Kos tetap tahunan pemilikan: ~RM110,000. Untuk break-even pada sewa RM620/hari, anda perlukan 178 hari guna — pada dasarnya kerja sepenuh masa setiap minggu.</p><h2 id="breakeven">Realiti Break-Even</h2><blockquote>Bawah 100 hari/tahun kerja skylift → sewa. 100–150 hari/tahun → masih sewa (hari terbiar bunuh ROI). Atas 150 hari/tahun berterusan → fikir beli, idealnya unit terpakai + operator khusus.</blockquote><p>Kebanyakan kontraktor SME dalam julat 30–80 hari. Sewa menang dengan jelas pada jumlah itu. {home_link('ms','Lihat fleet kami')} untuk kadar sewa terkini.</p><h2 id="cta">Sedia Tempah?</h2><p>Langkau CAPEX. WhatsApp kami bila perlukan unit:</p>{cta('ms')}<h2 id="conclusion">Penutup</h2><p>Beli bila guna berterusan atas 150 hari/tahun. Bawah itu, sewa lebih murah, lebih fleksibel, dan alihkan kos penyelenggaraan + operator kepada kami. Kebanyakan SME di {loc_link('ms','shah-alam','Shah Alam')} dan KL kekal sewa sahaja.</p>{cta('ms')}"""},
"zh":{"title":"租用 vs 购买高空车 — 中小承包商的成本分析","excerpt":"什么时候购买高空车比租用划算?马来西亚中小承包商的盈亏平衡数学。","meta_title":"租用还是购买高空车?成本分析 — Skylift Malaysia","meta_desc":"马来西亚中小承包商应租用还是购买高空车?盈亏平衡分析涵盖资本支出、折旧、维护、闲置天数。","body":f"""{toc('zh',[('intro','简介'),('rent','租用数学'),('buy','购买数学'),('breakeven','盈亏平衡点'),('cta','准备预订?'),('conclusion','总结')])}<h2 id="intro">简介</h2><p>您一个月接了 5 单高空车工作,开始问 — 我们干脆买一台吧?这是每位中小承包商签署融资租赁前应跑的数学。</p>{img(1238864,'承包商场地停放的高空车')}<h2 id="rent">租用数学</h2><p>20m 高空车租用:RM620/天全天或 RM500/天半天。一年租 80 天(单一承包商重档期):年度成本 ≈ RM50,000。操作员、燃料、保险、折旧 — 全在我们身上。</p><h2 id="buy">购买数学</h2><p>全新 20m 臂式卡车:RM450k–RM550k。二手(5 年):RM200k–RM280k。加上:<strong>保险 ~RM8k/年 · 路税 + 许可证 ~RM3k · 操作员工资 ~RM3k/月 · 维护 ~RM10k/年 · 折旧 ~RM45k/年(第 1 年)。</strong></p><p>拥有的年度固定成本:~RM110,000。要在 RM620/天租金上盈亏平衡,需要 178 天利用率 — 基本上每个工作周全职。</p><h2 id="breakeven">盈亏平衡现实</h2><blockquote>低于每年 100 天高空车工作 → 租用。100–150 天/年 → 仍租用(闲置天扼杀 ROI)。持续超过 150 天/年 → 考虑购买,最好是二手机型 + 专属操作员。</blockquote><p>大多数中小承包商在 30–80 天范围内。租用在这个数量上明显胜出。{home_link('zh','浏览我们的车队')} 获取当前租金。</p><h2 id="cta">准备预订?</h2><p>跳过资本支出。需要机型时 WhatsApp 我们:</p>{cta('zh')}<h2 id="conclusion">总结</h2><p>持续利用率超过 150 天/年时购买。低于此时,租用更便宜、更灵活,并将维护 + 操作员开销转给我们。{loc_link('zh','shah-alam','莎阿南')} 和 KL 的大多数中小企业坚持租用。</p>{cta('zh')}"""}}

# ===== Article 11 — JB-specific =====
A11 = {"slug":"skylift-rental-johor-bahru-everything-you-need-to-know","cover":PEXELS(273209),
"en":{"title":"Skylift Rental in Johor Bahru — Everything You Need to Know","excerpt":"Daily rates, dispatch zones, common job types, and same-day delivery details for skylift rental in Johor Bahru and southern Johor.","meta_title":"Skylift Rental Johor Bahru — Skylift Malaysia","meta_desc":"Skylift rental in Johor Bahru: rates, dispatch zones, popular job types, customs-zone work near Singapore border, JB depot details.","body":f"""{toc('en',[('intro','Introduction'),('rates','JB Rental Rates'),('common','Common JB Jobs'),('dispatch','Dispatch & Lead Time'),('cta','Ready to book?'),('conclusion','Conclusion')])}<h2 id="intro">Introduction</h2><p>Johor Bahru's mix of high-rise residential, industrial estates, and the Singapore-border customs zone makes it one of our busiest rental markets outside the Klang Valley. Here's everything you need to know about renting a skylift in JB.</p>{img(1216597,'Skylift truck working on JB shopfront')}<h2 id="rates">JB Rental Rates</h2><p>Same headline pricing as KL/Selangor — RM380/day for 9m, RM500 half / RM620 full for 20m, RM500 half / RM650 full for 24m, from RM1,200/day for 32m, RM850/day for spider lift. Operator, fuel, insurance always included.</p><p>Out-of-state surcharge: none for JB metro. Outer Johor (Kluang, Mersing) adds RM150 mobilisation.</p><h2 id="common">Common JB Jobs</h2><h3>1. Senai industrial roof maintenance</h3><p>20m and 24m booms are workhorses for the factory belt around Senai airport.</p><h3>2. Customs zone signage near CIQ</h3><p>32m for the towering CIQ approach signs. Permits required — we handle the application.</p><h3>3. JB City high-rise residential</h3><p>24m boom for facade work on Bukit Indah and Tebrau condos.</p><h3>4. Plaza Sentosa & Komtar mall maintenance</h3><p>Spider lift after closing hours for ceiling and atrium work.</p><h2 id="dispatch">Dispatch & Lead Time</h2><blockquote>Same-day in JB metro (Skudai, Tampoi, Tebrau, Permas Jaya, Pasir Gudang). Next-day in outer Johor. Booking by 10am secures same-day deployment.</blockquote><h2 id="cta">Ready to Book?</h2><p>{loc_link('en','johor-bahru','See JB-specific rental options')} or chat now:</p>{cta('en')}<h2 id="conclusion">Conclusion</h2><p>JB rental works the same way as KL — fixed pricing, certified operator, fast dispatch. Just give us the address and the height required.</p>{cta('en')}"""},
"ms":{"title":"Sewa Skylift di Johor Bahru — Semua Yang Anda Perlu Tahu","excerpt":"Kadar harian, zon dispatch, jenis kerja biasa, dan butiran penghantaran hari sama untuk sewa skylift di Johor Bahru.","meta_title":"Sewa Skylift Johor Bahru — Skylift Malaysia","meta_desc":"Sewa skylift di Johor Bahru: kadar, zon dispatch, jenis kerja popular, kerja zon kastam dekat sempadan Singapura, butiran depot JB.","body":f"""{toc('ms',[('intro','Pengenalan'),('rates','Kadar Sewa JB'),('common','Kerja Biasa JB'),('dispatch','Dispatch & Masa Tunggu'),('cta','Sedia tempah?'),('conclusion','Penutup')])}<h2 id="intro">Pengenalan</h2><p>Campuran pangsapuri tinggi, kawasan perindustrian, dan zon kastam sempadan Singapura di JB jadikan ia salah satu pasaran sewa paling sibuk di luar Lembah Klang. Berikut semua yang anda perlu tahu tentang sewa skylift di JB.</p>{img(1216597,'Skylift di papan kedai JB')}<h2 id="rates">Kadar Sewa JB</h2><p>Harga utama sama dengan KL/Selangor — RM380/hari untuk 9m, RM500 separuh / RM620 penuh untuk 20m, RM500 separuh / RM650 penuh untuk 24m, dari RM1,200/hari untuk 32m, RM850/hari untuk spider lift. Operator, minyak, insurans sentiasa termasuk.</p><p>Caj tambahan luar negeri: tiada untuk metro JB. Johor luar (Kluang, Mersing) tambah RM150 mobilisasi.</p><h2 id="common">Kerja Biasa JB</h2><h3>1. Penyelenggaraan bumbung industri Senai</h3><p>Boom 20m dan 24m kerja kuda untuk lingkaran kilang sekitar lapangan terbang Senai.</p><h3>2. Papan tanda zon kastam dekat CIQ</h3><p>32m untuk papan pendekatan CIQ yang tinggi. Permit diperlukan — kami uruskan permohonan.</p><h3>3. Pangsapuri tinggi JB City</h3><p>Boom 24m untuk kerja fasad kondo Bukit Indah dan Tebrau.</p><h3>4. Penyelenggaraan Plaza Sentosa & Komtar</h3><p>Spider lift selepas tutup untuk kerja siling dan atrium.</p><h2 id="dispatch">Dispatch & Masa Tunggu</h2><blockquote>Hari sama dalam metro JB (Skudai, Tampoi, Tebrau, Permas Jaya, Pasir Gudang). Hari berikutnya untuk Johor luar. Tempahan sebelum 10 pagi pastikan susun atur hari sama.</blockquote><h2 id="cta">Sedia Tempah?</h2><p>{loc_link('ms','johor-bahru','Lihat pilihan sewa khusus JB')} atau berbual sekarang:</p>{cta('ms')}<h2 id="conclusion">Penutup</h2><p>Sewa di JB berjalan sama macam KL — harga tetap, operator bertauliah, dispatch pantas. Beri sahaja alamat dan ketinggian.</p>{cta('ms')}"""},
"zh":{"title":"新山高空车租用 — 您需要知道的一切","excerpt":"新山及南柔佛高空车租用的日租、派遣区域、常见工程类型与当天送达详情。","meta_title":"新山高空车租用 — Skylift Malaysia","meta_desc":"新山高空车租用:费率、派遣区、热门工程、新加坡边境关税区作业、新山车场详情。","body":f"""{toc('zh',[('intro','简介'),('rates','新山租金'),('common','新山常见工程'),('dispatch','派遣与提前期'),('cta','准备预订?'),('conclusion','总结')])}<h2 id="intro">简介</h2><p>新山的高层公寓、工业区与新加坡边境关税区交融,是雪隆以外最忙碌的租用市场之一。以下是您在新山租用高空车需要知道的一切。</p>{img(1216597,'新山店面工作的高空车')}<h2 id="rates">新山租金</h2><p>主要价格与 KL/雪兰莪相同 — 9m RM380/天、20m 半天 RM500 / 全天 RM620、24m 半天 RM500 / 全天 RM650、32m 起 RM1,200/天、蜘蛛车 RM850/天。操作员、燃油、保险均含。</p><p>外州附加费:新山都市无。外柔佛(居銮、丰盛港)加 RM150 调度费。</p><h2 id="common">新山常见工程</h2><h3>1. 士乃工业屋顶维护</h3><p>20m 和 24m 臂式机是士乃机场周围工厂带的主力。</p><h3>2. CIQ 附近关税区招牌</h3><p>32m 用于高耸的 CIQ 进近招牌。需许可证 — 我们代办申请。</p><h3>3. 新山市高层公寓</h3><p>24m 臂式机用于武吉英达和地不佬公寓的立面工作。</p><h3>4. 五福城与广场商场维护</h3><p>蜘蛛车在闭店后用于天花板和中庭工作。</p><h2 id="dispatch">派遣与提前期</h2><blockquote>新山都市当天(士古来、淡杯、地不佬、巴莪、巴西古当)。外柔佛次日。10 点前预订确保当天部署。</blockquote><h2 id="cta">准备预订?</h2><p>{loc_link('zh','johor-bahru','查看新山特定租用方案')} 或现在咨询:</p>{cta('zh')}<h2 id="conclusion">总结</h2><p>新山租用与 KL 一样 — 固定价格、持证操作员、快速派遣。提供地址和所需高度即可。</p>{cta('zh')}"""}}

# ===== Article 12 — Monsoon season tips =====
A12 = {"slug":"monsoon-season-skylift-rental-tips-for-malaysian-contractors","cover":PEXELS(416405),
"en":{"title":"Monsoon Season Skylift Rental Tips for Malaysian Contractors","excerpt":"How to plan skylift rentals around Malaysia's monsoon. Wind safety thresholds, lightning protocols, ground-bearing prep for wet sites.","meta_title":"Monsoon Season Skylift Tips Malaysia — Skylift Malaysia","meta_desc":"Monsoon-season skylift rental in Malaysia: wind limits, lightning safety, soft-ground outrigger prep, weekly schedule planning.","body":f"""{toc('en',[('intro','Introduction'),('weather','Weather Limits'),('prep','Site Prep'),('cta','Ready to book?'),('schedule','Schedule Buffers'),('conclusion','Conclusion')])}<h2 id="intro">Introduction</h2><p>October to March is monsoon season across most of Peninsular Malaysia, and especially severe on the East Coast. Skylift rentals don't stop — but they do need extra planning. Here's how to keep work on track when the rain comes.</p>{img(532170,'Skylift rental in light rain on construction site')}<h2 id="weather">Weather Limits</h2><h3>Wind</h3><p>Boom lifts must be lowered above 12.5 m/s (28 mph). Pre-monsoon mornings frequently spike past this — check forecasts daily.</p><h3>Lightning</h3><p>If thunder is audible, the basket comes down immediately. Standard rule: no aerial work within 30 minutes of last lightning strike within 10km.</p><h3>Heavy rain</h3><p>Light rain is fine; heavy rain reduces operator visibility and makes platforms slippery. Most jobs pause when rainfall exceeds 5mm/hour.</p><h2 id="prep">Site Prep for Wet Conditions</h2><blockquote>Outrigger pads on every leg. Check soil bearing — soft ground sinks faster after rain. Protect electrical work from drip lines. Pause during active downpours.</blockquote><p>For factory roof inspection in {loc_link('en','shah-alam','Shah Alam')} during monsoon, we always bring extended outrigger pads and a tarp for the basket.</p><h2 id="cta">Ready to Book?</h2><p>Monsoon won't stop us — but we'll plan around it. WhatsApp:</p>{cta('en')}<h2 id="schedule">Schedule Buffers</h2><p>Build a 25% time buffer into monsoon-season project schedules. A 4-day signage refit becomes a 5-day plan. The buffer absorbs short rain pauses without missing the deadline.</p><h2 id="conclusion">Conclusion</h2><p>Smart planning beats weather. Tell us your project window and we'll suggest the right unit and schedule for monsoon conditions.</p>{cta('en')}"""},
"ms":{"title":"Tip Sewa Skylift Musim Tengkujuh untuk Kontraktor Malaysia","excerpt":"Cara rancang sewa skylift sekitar musim tengkujuh Malaysia. Ambang keselamatan angin, protokol kilat, persediaan tanah untuk tapak basah.","meta_title":"Tip Skylift Musim Tengkujuh Malaysia — Skylift Malaysia","meta_desc":"Sewa skylift musim tengkujuh di Malaysia: had angin, keselamatan kilat, persediaan outrigger tanah lembut, perancangan jadual mingguan.","body":f"""{toc('ms',[('intro','Pengenalan'),('weather','Had Cuaca'),('prep','Persediaan Tapak'),('cta','Sedia tempah?'),('schedule','Buffer Jadual'),('conclusion','Penutup')])}<h2 id="intro">Pengenalan</h2><p>Oktober hingga Mac ialah musim tengkujuh di kebanyakan Semenanjung, dan terutama teruk di Pantai Timur. Sewa skylift tidak berhenti — tetapi memerlukan perancangan tambahan. Berikut cara pastikan kerja berjalan apabila hujan turun.</p>{img(532170,'Sewa skylift dalam hujan ringan di tapak pembinaan')}<h2 id="weather">Had Cuaca</h2><h3>Angin</h3><p>Boom lift mesti diturunkan atas 12.5 m/s (28 mph). Pagi pra-tengkujuh selalu naik melepasi ini — semak ramalan setiap hari.</p><h3>Kilat</h3><p>Kalau guruh boleh didengar, bakul diturunkan segera. Peraturan asas: tiada kerja udara dalam 30 minit dari sambaran kilat terakhir dalam 10km.</p><h3>Hujan lebat</h3><p>Hujan ringan tak apa; hujan lebat kurangkan penglihatan operator dan platform jadi licin. Kebanyakan kerja jeda bila hujan melebihi 5mm/jam.</p><h2 id="prep">Persediaan Tapak Basah</h2><blockquote>Pad outrigger setiap kaki. Semak daya tampung tanah — tanah lembut tenggelam lebih cepat selepas hujan. Lindungi kerja elektrik dari titisan. Jeda semasa hujan aktif.</blockquote><p>Untuk pemeriksaan bumbung kilang di {loc_link('ms','shah-alam','Shah Alam')} musim tengkujuh, kami sentiasa bawa pad outrigger lanjutan dan tarpaulin bakul.</p><h2 id="cta">Sedia Tempah?</h2><p>Tengkujuh tidak hentikan kami — tapi kami akan rancang sekitar ia. WhatsApp:</p>{cta('ms')}<h2 id="schedule">Buffer Jadual</h2><p>Bina buffer masa 25% dalam jadual projek musim tengkujuh. Pemasangan papan tanda 4 hari jadi pelan 5 hari. Buffer menyerap jeda hujan pendek tanpa terlepas tarikh akhir.</p><h2 id="conclusion">Penutup</h2><p>Perancangan bijak kalahkan cuaca. Beritahu tetingkap projek dan kami cadang unit serta jadual yang betul untuk keadaan tengkujuh.</p>{cta('ms')}"""},
"zh":{"title":"马来西亚承包商的雨季高空车租用建议","excerpt":"如何在马来西亚雨季规划高空车租用。风速安全阈值、雷电协议、湿地地面承重准备。","meta_title":"雨季高空车建议马来西亚 — Skylift Malaysia","meta_desc":"马来西亚雨季高空车租用:风速限制、雷电安全、软地支腿准备、周计划。","body":f"""{toc('zh',[('intro','简介'),('weather','天气限制'),('prep','工地准备'),('cta','准备预订?'),('schedule','计划缓冲'),('conclusion','总结')])}<h2 id="intro">简介</h2><p>10 月到 3 月是西马大部分地区的雨季,东海岸尤其严重。高空车租用不停 — 但需要额外规划。以下是如何在下雨时让工作按计划进行。</p>{img(532170,'工地小雨中的高空车')}<h2 id="weather">天气限制</h2><h3>风</h3><p>风速超过 12.5 m/s(28 mph)时臂式车必须降下。雨季前的早晨经常突破此值 — 每天查看天气预报。</p><h3>雷电</h3><p>能听到雷声时,平台立即降下。基本规则:10 公里内最近一次闪电后 30 分钟内不进行高空作业。</p><h3>大雨</h3><p>小雨没问题;大雨降低操作员能见度并使平台滑。降雨量超过 5mm/小时时大多数工作暂停。</p><h2 id="prep">湿地工地准备</h2><blockquote>每条支腿垫板。检查土壤承载力 — 软土在雨后下沉更快。保护电气工作免受滴水线影响。在主动下雨期间暂停。</blockquote><p>雨季在 {loc_link('zh','shah-alam','莎阿南')} 工厂屋顶检查时,我们总会带加长支腿垫板和平台防雨布。</p><h2 id="cta">准备预订?</h2><p>雨季阻不了我们 — 但我们会围绕它规划。WhatsApp:</p>{cta('zh')}<h2 id="schedule">计划缓冲</h2><p>在雨季项目时间表中加入 25% 时间缓冲。4 天的招牌改装变成 5 天计划。缓冲吸收短暂的雨停而不错过截止日期。</p><h2 id="conclusion">总结</h2><p>聪明的规划胜过天气。告诉我们项目窗口,我们会为雨季条件推荐合适的机型和时间表。</p>{cta('zh')}"""}}

posts = [A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12]
print(f"draft posts so far: {len(posts)} — should be 12")

with open(OUT, "w", encoding="utf-8") as f:
    json.dump({"posts": [
        {"slug": p["slug"], "cover_image_url": p["cover"], "translations": [
            {"language": l, "title": p[l]["title"], "content": p[l]["body"].strip(),
             "excerpt": p[l]["excerpt"], "meta_title": p[l]["meta_title"], "meta_description": p[l]["meta_desc"]}
            for l in ("en","ms","zh")]
        } for p in posts
    ]}, f, ensure_ascii=False, indent=2)
print(f"wrote {OUT} with {len(posts)} posts")
