import { siteConfig } from '@/config/site'
import { routing } from '@/i18n/routing'

/**
 * Social share card — a 1200x630 screenshot of the hero section, one per locale
 * (`public/og-{locale}.png`), generated by `scripts/og-shot.mjs`.
 *
 * Regenerate after ANY hero copy / image / palette change. The card is a
 * screenshot, so a stale one is invisible: the site looks right and only the
 * shared link is wrong.
 *
 * The URL is built ABSOLUTE from `siteConfig.baseUrl`. The canonical template
 * leans on `metadataBase`, but this project never sets one, and a relative
 * og:image is rejected by most scrapers.
 *
 * Locales come from `routing`, not `siteConfig`: this project keeps the locale
 * list in i18n/routing.ts only, and `defaultLocale` here is EN (not MS as in
 * most of the fleet).
 *
 * Next.js replaces a parent's `openGraph` object WHOLESALE when a page defines
 * its own, so every page that sets `openGraph` must spread this in explicitly.
 * Inheriting it from the layout does NOT work — that is exactly how sites ship
 * with a share card on the homepage and none on location or blog pages.
 */
export function ogImage(locale: string, alt?: string) {
  const known = (routing.locales as readonly string[]).includes(locale)
  return {
    url: `${siteConfig.baseUrl}/og-${known ? locale : routing.defaultLocale}.png`,
    width: 1200,
    height: 630,
    alt: alt ?? siteConfig.brandName,
  }
}

/**
 * Ready-to-spread `images` array for `openGraph` / `twitter`.
 * `alt` is optional so a page can describe its own card.
 */
export function ogImages(locale: string, alt?: string) {
  return [ogImage(locale, alt)]
}
