import { siteConfig } from '@/config/site'
import { routing } from '@/i18n/routing'

/**
 * Social share card — a 1200x630 screenshot of the hero section, one per locale
 * (`public/og-{locale}.png`), generated by `scripts/og-shot.mjs`.
 *
 * Regenerate after ANY hero copy / image / palette change. The card is a
 * screenshot, so a stale one is invisible: the site looks right and only the
 * shared link is wrong.
 *
 * Relative URLs resolve against the `metadataBase` each page already sets from
 * `siteConfig.url` — without it the card URL comes out relative and most
 * scrapers reject it.
 *
 * Locales come from `routing`, not `siteConfig`: this project keeps the locale
 * list in i18n/routing.ts only, and `defaultLocale` here is EN (not MS as in
 * most of the fleet).
 *
 * Next.js replaces a parent's `openGraph` object WHOLESALE when a page defines
 * its own, so every page that sets `openGraph` must spread this in explicitly.
 * Inheriting it from the layout does NOT work — that is exactly how sites ship
 * with a share card on the homepage and none on location or blog pages.
 */
export function ogImage(locale: string) {
  const known = (routing.locales as readonly string[]).includes(locale)
  return {
    url: `/og-${known ? locale : routing.defaultLocale}.png`,
    width: 1200,
    height: 630,
    alt: siteConfig.brandName,
  }
}

/** Ready-to-spread `images` array for `openGraph` / `twitter`. */
export function ogImages(locale: string) {
  return [ogImage(locale)]
}
