// ─────────────────────────────────────────────────────────────────────────
// Build Playbook — the website-builder system decomposed into layers + units.
//
// Grounded in CLAUDE.md, docs/website-building-flow.md, docs/full-website-setup.md
// and the agent definitions in agents/. Each unit carries a maturity score, an
// owning agent, a 12-field spec, and links to the source markdown so the
// playbook stays traceable to the repo.
//
// Maturity bands:  🟢 mature ≥ 75   🟡 partial 45–74   🔴 gap < 45
// ─────────────────────────────────────────────────────────────────────────

export const GH_BASE =
  'https://github.com/atyn-utopia/utopia-website-builder/blob/main/'

export interface DocLink {
  label: string
  path: string // repo-relative; resolved against GH_BASE
}

export interface UnitSpec {
  purpose: string
  scope: string
  triggers: string
  inputs: string
  steps: string
  outputs: string
  variants: string
  guardrails: string
  integrations: string
  completion: string
  examples: string
  openItems: string
}

export interface Unit {
  name: string
  owner: string
  ownerPath: string // agent md
  maturity: number // 0–100
  spec: UnitSpec
  docs: DocLink[]
}

export interface Layer {
  id: number
  name: string
  subtitle: string
  phase: 'BUILD' | 'DATA' | 'SHIP'
  units: Unit[]
}

// Shorthand agent → md path
const A = {
  alpha: 'agents/alpha.md',
  cyclops: 'agents/cyclops.md',
  sora: 'agents/sora.md',
  nana: 'agents/nana.md',
  kagura: 'agents/kagura.md',
  kimmy: 'agents/kimmy.md',
  hanabi: 'agents/hanabi.md',
  layla: 'agents/layla.md',
  human: 'docs/full-website-setup.md',
}

// Common docs
const CLAUDE: DocLink = { label: 'CLAUDE.md', path: 'CLAUDE.md' }
const FLOW: DocLink = { label: 'Flow', path: 'docs/website-building-flow.md' }
const SETUP: DocLink = { label: 'Setup', path: 'docs/full-website-setup.md' }
const TRACK: DocLink = { label: 'Tracking', path: 'docs/tracking-guide.md' }
const GUARD: DocLink = { label: 'Guardrails', path: 'docs/guardrails.html' }
const NEWSITE: DocLink = { label: 'New-website', path: 'prompts/new-website.md' }
const ORCH: DocLink = { label: 'Orchestrate', path: 'prompts/orchestrate.md' }
const SELFCHK: DocLink = { label: 'Self-check', path: 'prompts/agent-self-check.md' }
const CHROME: DocLink = { label: 'site-chrome', path: 'templates/site-chrome' }
const BLOGTPL: DocLink = { label: 'blog template', path: 'templates/blog' }

const agentDoc = (path: string, name: string): DocLink => ({ label: name, path })

export const LAYERS: Layer[] = [
  // ── LAYER 0 ──────────────────────────────────────────────────────────────
  {
    id: 0,
    name: 'Inputs & Brand Kit',
    subtitle: 'Step 0 — gather everything before a single file is written.',
    phase: 'BUILD',
    units: [
      {
        name: 'Business Intake',
        owner: 'Alpha',
        ownerPath: A.alpha,
        maturity: 60,
        spec: {
          purpose: 'Capture every project input into inputs.md so the build is reproducible.',
          scope: 'Company, product name + slug, brand, locations, languages, WhatsApp number, leads mode, assets.',
          triggers: 'User requests a new website.',
          inputs: 'Free-form brief from the user.',
          steps: 'Interview → fill the generated inputs.md → confirm gaps with the user.',
          outputs: 'projects/{slug}/inputs.md fully populated.',
          variants: 'Single vs multi-product; emergency vs standard service.',
          guardrails: 'Never invent inputs; ask if missing (esp. phone + domain).',
          integrations: 'Feeds every downstream agent.',
          completion: 'inputs.md has no TODO/placeholder fields.',
          examples: 'electrician-24-hour, roller-shutter-malaysia.',
          openItems: 'No structured intake form yet — still conversational.',
        },
        docs: [SETUP, NEWSITE, agentDoc(A.alpha, 'Alpha')],
      },
      {
        name: 'Vercel Domain Verification',
        owner: 'Alpha',
        ownerPath: A.alpha,
        maturity: 82,
        spec: {
          purpose: 'Lock the REAL domain Vercel serves before anything references it.',
          scope: 'config/site.ts domain, deploy-url.txt, data-website, DB website column.',
          triggers: 'Step 0, re-checked at ship.',
          inputs: 'Vercel project alias.',
          steps: 'Query Vercel for the served alias → set it everywhere identically.',
          outputs: 'One canonical domain string used by code + DB.',
          variants: 'hyphenated vs non-hyphenated alias collisions.',
          guardrails: 'vercel-domain-match fails the gate on any mismatch.',
          integrations: 'Webcore queries key on this exact domain.',
          completion: 'vercel-domain-match passes.',
          examples: 'roller-shutter → rollershutter alias fix.',
          openItems: 'Verification is manual at Step 0; only enforced at ship.',
        },
        docs: [FLOW, SETUP, GUARD],
      },
      {
        name: 'Brand Assets (logo / colour / font)',
        owner: 'Kagura',
        ownerPath: A.kagura,
        maturity: 45,
        spec: {
          purpose: 'Source real logos, palette and typography before design starts.',
          scope: 'brand_assets/, /public/brand/, globals.css tokens.',
          triggers: 'Before Kagura sets design direction.',
          inputs: 'Client-provided assets or designer choice.',
          steps: 'Collect/produce logo + palette + fonts → place in brand_assets/.',
          outputs: 'Usable brand kit referenced by tokens.',
          variants: 'Client assets provided vs designed from scratch.',
          guardrails: 'Use real assets when present; never replace with placeholders; never re-encode PNG→JPEG.',
          integrations: 'Drives Design Tokens + Hero.',
          completion: 'Logo, palette, ≥2 fonts committed.',
          examples: 'Per-project brand_assets/ folders.',
          openItems: 'No automated logo/colour generation — mostly manual.',
        },
        docs: [CLAUDE, agentDoc(A.kagura, 'Kagura')],
      },
      {
        name: 'Favicon = Logo Icon',
        owner: 'Kimmy',
        ownerPath: A.kimmy,
        maturity: 55,
        spec: {
          purpose: 'The icon inside the logo IS the favicon — one consistent mark.',
          scope: 'app/icon.svg + logo.',
          triggers: 'After logo exists.',
          inputs: 'Logo icon element.',
          steps: 'Isolate the icon → ship as app/icon.svg → confirm 16/32px legibility.',
          outputs: 'app/icon.svg matching the logo.',
          variants: 'Provided logo vs designed-from-scratch (icon first).',
          guardrails: 'Icon must read standalone at small sizes.',
          integrations: 'Browser tab + PWA.',
          completion: 'Favicon visually matches logo icon.',
          examples: 'All project app/icon.svg files.',
          openItems: 'No automated icon extraction.',
        },
        docs: [CLAUDE, agentDoc(A.kimmy, 'Kimmy')],
      },
      {
        name: 'Language Set (ms / en / zh)',
        owner: 'Kimmy',
        ownerPath: A.kimmy,
        maturity: 85,
        spec: {
          purpose: 'Fix the locale set + default before copy is written.',
          scope: 'config/site.ts locales, messages/{ms,en,zh}.json, routing.',
          triggers: 'Confirmed by Alpha with the user.',
          inputs: 'Target market languages.',
          steps: 'Set defaultLocale + locales → scaffold message files.',
          outputs: 'Three-locale i18n skeleton.',
          variants: 'ms-default vs en-default markets.',
          guardrails: 'All three locales must stay key-complete.',
          integrations: 'next-intl middleware + language switcher.',
          completion: 'All locales resolve with no missing keys.',
          examples: 'ms default across Malaysian projects.',
          openItems: '—',
        },
        docs: [CLAUDE, SETUP, agentDoc(A.kimmy, 'Kimmy')],
      },
      {
        name: 'Locations Config (150–180 towns)',
        owner: 'Sora',
        ownerPath: A.sora,
        maturity: 80,
        spec: {
          purpose: 'Define the real towns each location page is generated for.',
          scope: 'config/locations.ts (≥10 per state, 150–180 total).',
          triggers: 'After states/coverage decided.',
          inputs: 'Service coverage area.',
          steps: 'List real towns per state → group by region → wire nearbyMap.',
          outputs: 'Location set powering generateStaticParams + sitemap.',
          variants: 'National vs regional coverage.',
          guardrails: 'Real towns only; 150–180 total; ≥10/state; every town in sitemap.',
          integrations: 'Location pages, sitemap, hub-spoke SEO.',
          completion: 'Count in range; all towns emit a page.',
          examples: 'Per-project config/locations.ts.',
          openItems: 'Town lists curated manually.',
        },
        docs: [CLAUDE, SETUP, agentDoc(A.sora, 'Sora')],
      },
      {
        name: 'Leads Mode Choice',
        owner: 'Cyclops',
        ownerPath: A.cyclops,
        maturity: 78,
        spec: {
          purpose: 'Pick how WhatsApp numbers are selected (single / rotation / location / hybrid).',
          scope: 'company_websites.leads_mode.',
          triggers: 'During project setup.',
          inputs: 'Sales team structure.',
          steps: 'Ask the user → set leads_mode → seed phone rows.',
          outputs: 'leads_mode set + default number seeded.',
          variants: 'single | rotation | location | hybrid.',
          guardrails: 'Default to single; one active default number minimum.',
          integrations: 'redirect-whatsapp-1 routing logic.',
          completion: 'Row exists; mode chosen; number active.',
          examples: 'Regional teams → location/hybrid.',
          openItems: '—',
        },
        docs: [CLAUDE, SETUP, agentDoc(A.cyclops, 'Cyclops')],
      },
    ],
  },

  // ── LAYER 1 ──────────────────────────────────────────────────────────────
  {
    id: 1,
    name: 'Scaffold & Architecture',
    subtitle: 'Step 1 — clone the canonical skeleton; start at ~96/100.',
    phase: 'BUILD',
    units: [
      {
        name: 'Scaffolder (npm run scaffold)',
        owner: 'Alpha',
        ownerPath: A.alpha,
        maturity: 92,
        spec: {
          purpose: 'Replace empty-folder + create-next-app with a prevent-by-construction clone.',
          scope: 'utopia-wizard scaffold-site.ts → projects/{slug}.',
          triggers: 'After inputs gathered.',
          inputs: 'slug, brand, product, product-slug, domain, phone.',
          steps: 'Run scaffold → symlink .env.local → npm install → update inputs.md.',
          outputs: 'New site at ~96/100, zero blocking failures.',
          variants: 'Emergency vs standard product templates.',
          guardrails: 'Chrome only from templates/site-chrome (single source).',
          integrations: 'Feeds the whole agent pipeline.',
          completion: 'Scaffold builds + source-only gate clean.',
          examples: 'Every project after the scaffold rollout.',
          openItems: '—',
        },
        docs: [FLOW, SETUP, NEWSITE],
      },
      {
        name: 'Canonical Chrome',
        owner: 'Kimmy',
        ownerPath: A.kimmy,
        maturity: 90,
        spec: {
          purpose: 'One header/footer/fomo/lang-switcher/WA-button for every site.',
          scope: 'templates/site-chrome → SiteHeader, SiteFooter, FomoBanner, PageStyles, LanguageSwitcher, WhatsAppButton.',
          triggers: 'Placed at scaffold.',
          inputs: 'Brand name, logo, locale labels.',
          steps: 'Copy chrome → swap brand assets only.',
          outputs: 'Identical chrome on home / location / blog.',
          variants: 'None — per-page nav variants (BlogNav) are forbidden.',
          guardrails: 'site-chrome-components, no-blognav-usage, *-chrome checks.',
          integrations: 'Every public page.',
          completion: 'chrome:check reports no drift.',
          examples: 'sewa-excavator canonical chrome.',
          openItems: 'Legacy sites need a 3-layer migration.',
        },
        docs: [FLOW, CHROME, GUARD],
      },
      {
        name: 'System Architecture',
        owner: 'Alpha',
        ownerPath: A.alpha,
        maturity: 80,
        spec: {
          purpose: 'Decide routes, data flow and page hierarchy for the project.',
          scope: 'architecture.md, app/ route tree.',
          triggers: 'First agent step.',
          inputs: 'inputs.md + SEO plan.',
          steps: 'Define routes → data sources → ISR strategy.',
          outputs: 'architecture.md.',
          variants: 'Product depth, locale count.',
          guardrails: 'Tag-based ISR only (no time-based revalidate).',
          integrations: 'Guides Cyclops + Kimmy.',
          completion: 'Architecture confirms with the flow.',
          examples: 'Per-project architecture.md.',
          openItems: '—',
        },
        docs: [agentDoc(A.alpha, 'Alpha'), ORCH, FLOW],
      },
      {
        name: 'Webcore Data Layer',
        owner: 'Cyclops',
        ownerPath: A.cyclops,
        maturity: 85,
        spec: {
          purpose: 'Unified read layer for products / phones / blog with cache tags.',
          scope: 'lib/webcore.ts, revalidateTag.',
          triggers: 'Used by every dynamic page.',
          inputs: 'Domain + Supabase rows.',
          steps: 'Fetch with next.tags → invalidate via webhook → revalidateTag().',
          outputs: 'Fresh data without redeploy.',
          variants: 'products / phones / blog tags.',
          guardrails: 'no-time-revalidate; reads must go through webcore.',
          integrations: 'Supabase + admin webhook.',
          completion: 'Tag invalidation propagates changes.',
          examples: 'lib/webcore.ts in every project.',
          openItems: '—',
        },
        docs: [CLAUDE, agentDoc(A.cyclops, 'Cyclops')],
      },
      {
        name: 'Shared DB + Env Wiring',
        owner: 'Cyclops',
        ownerPath: A.cyclops,
        maturity: 82,
        spec: {
          purpose: 'All sites share ONE Supabase, distinguished by the website column.',
          scope: 'Root .env.local symlink, next.config.ts loadEnvConfig, Vercel env.',
          triggers: 'At scaffold + before deploy.',
          inputs: 'Root credentials.',
          steps: 'Symlink env → load from repo root → add Vercel env vars.',
          outputs: 'Working DB connection per site.',
          variants: 'Local vs Vercel env.',
          guardrails: 'Never create a per-site Supabase project.',
          integrations: 'Supabase, Vercel.',
          completion: 'Live DB reads succeed.',
          examples: 'Shared phone_numbers / products / blog_posts.',
          openItems: '—',
        },
        docs: [CLAUDE, SETUP],
      },
    ],
  },

  // ── LAYER 2 ──────────────────────────────────────────────────────────────
  {
    id: 2,
    name: 'Design System',
    subtitle: 'Tokens + a unique visual direction per project.',
    phase: 'BUILD',
    units: [
      {
        name: 'Design Tokens',
        owner: 'Kagura',
        ownerPath: A.kagura,
        maturity: 80,
        spec: {
          purpose: 'Project-scoped CSS variables so every component inherits one system.',
          scope: 'globals.css --brand-*, --ink-*, --gut, --radius-*, line-heights.',
          triggers: 'Before any page is built.',
          inputs: 'Brand palette + fonts.',
          steps: 'Define tokens → set heading 1.2 / body 1.4 line-heights.',
          outputs: 'Token foundation referenced everywhere.',
          variants: 'Per-project palettes.',
          guardrails: 'no-undefined-css-vars; never copy a page without remapping vars.',
          integrations: 'All sections + PageStyles.',
          completion: 'Every var(--x) is defined in this project.',
          examples: 'globals.css per project.',
          openItems: '—',
        },
        docs: [CLAUDE, FLOW, agentDoc(A.kagura, 'Kagura')],
      },
      {
        name: 'Design Direction',
        owner: 'Kagura',
        ownerPath: A.kagura,
        maturity: 62,
        spec: {
          purpose: 'Fix a unique look (avoid duplicate layouts across sites).',
          scope: 'design-direction.md — palette, fonts, hero treatment, special section.',
          triggers: 'After Nana copy, before page build.',
          inputs: 'Existing-site review + fresh inspiration.',
          steps: 'Review live sites → research → propose a distinct direction.',
          outputs: 'design-direction.md.',
          variants: 'Industry-specific moods.',
          guardrails: 'No default Tailwind blue/indigo; layered shadows; distinct heading font.',
          integrations: 'Guides page build + special section.',
          completion: 'Direction is documented + non-duplicate.',
          examples: 'Per-project design-direction.md.',
          openItems: 'Duplicate-detection is manual review.',
        },
        docs: [agentDoc(A.kagura, 'Kagura'), CLAUDE, FLOW],
      },
      {
        name: 'Anti-Generic Guardrails',
        owner: 'Kagura',
        ownerPath: A.kagura,
        maturity: 75,
        spec: {
          purpose: 'Keep craft high — no generic AI-looking output.',
          scope: 'Colours, shadows, typography, gradients, motion, states, depth.',
          triggers: 'Throughout page build.',
          inputs: 'Design tokens.',
          steps: 'Apply layered shadows, tight heading tracking, transform/opacity-only animation, hover/focus/active states.',
          outputs: 'Distinctive, layered surfaces.',
          variants: '—',
          guardrails: 'No transition-all; no flat shadow-md; serif/display heading + sans body.',
          integrations: 'All interactive elements.',
          completion: 'Anti-generic rules satisfied in review.',
          examples: 'CLAUDE.md Anti-Generic section.',
          openItems: 'Not all rules are machine-checked.',
        },
        docs: [CLAUDE, agentDoc(A.kagura, 'Kagura')],
      },
    ],
  },

  // ── LAYER 3 ──────────────────────────────────────────────────────────────
  {
    id: 3,
    name: 'Copy & Content',
    subtitle: 'SEO copy, metadata and translations for every page.',
    phase: 'BUILD',
    units: [
      {
        name: 'SEO Copywriting',
        owner: 'Nana',
        ownerPath: A.nana,
        maturity: 80,
        spec: {
          purpose: 'Write homepage + every location page + meta copy.',
          scope: 'copy-homepage.md, copy-locations.md, messages/*.',
          triggers: 'After Alpha + Sora.',
          inputs: 'Keyword plan + architecture.',
          steps: 'Draft homepage → unique copy per city → meta copy.',
          outputs: 'All page copy in three locales.',
          variants: 'Per-city localisation.',
          guardrails: 'Unique per-location copy; keyword placement in headings; no duplicate content.',
          integrations: 'i18n message files.',
          completion: 'Every location has unique copy.',
          examples: 'copy-locations.md per project.',
          openItems: '—',
        },
        docs: [agentDoc(A.nana, 'Nana'), CLAUDE],
      },
      {
        name: 'Keyword Hierarchy',
        owner: 'Sora',
        ownerPath: A.sora,
        maturity: 78,
        spec: {
          purpose: 'Plan keyword structure + internal-link hierarchy.',
          scope: 'seo-plan.md.',
          triggers: 'Parallel with Cyclops after Alpha.',
          inputs: 'Product + locations + languages.',
          steps: 'Map primary/secondary keywords → page hierarchy → internal links.',
          outputs: 'seo-plan.md.',
          variants: 'Per-language keyword sets.',
          guardrails: 'Heading level is keyword-driven; every H3/eyebrow carries a primary keyword.',
          integrations: 'Drives copy + schema.',
          completion: 'Keyword map covers all pages.',
          examples: 'seo-plan.md per project.',
          openItems: '—',
        },
        docs: [agentDoc(A.sora, 'Sora'), CLAUDE],
      },
      {
        name: 'Metadata & Meta Copy',
        owner: 'Kimmy',
        ownerPath: A.kimmy,
        maturity: 76,
        spec: {
          purpose: 'Title, description, canonical, OG per route + locale.',
          scope: 'generateMetadata, messages metadata block.',
          triggers: 'During page build.',
          inputs: 'Keyword + copy.',
          steps: 'Set title/description → canonical + hreflang → OG.',
          outputs: 'Per-route metadata.',
          variants: 'Home / location / blog metadata.',
          guardrails: 'Unique meta title + description per page.',
          integrations: 'Next metadata API.',
          completion: 'Meta present on every route.',
          examples: 'electric-wheelchair metadata.',
          openItems: '—',
        },
        docs: [agentDoc(A.kimmy, 'Kimmy'), SETUP],
      },
      {
        name: 'i18n Translations',
        owner: 'Kimmy',
        ownerPath: A.kimmy,
        maturity: 80,
        spec: {
          purpose: 'Key-complete ms/en/zh message files with no bare literals.',
          scope: 'messages/{ms,en,zh}.json + next-intl.',
          triggers: 'After copy.',
          inputs: 'Nana copy.',
          steps: 'Key all visible strings → translate → wire t().',
          outputs: 'Three locale files in sync.',
          variants: 'CJK exempt from CTA word-limit.',
          guardrails: 'No hardcoded English in JSX (the USP-bar class of bug).',
          integrations: 'Language switcher + routing.',
          completion: 'All locales resolve; no missing keys.',
          examples: 'roller-shutter USP localisation fix.',
          openItems: '—',
        },
        docs: [CLAUDE, agentDoc(A.kimmy, 'Kimmy')],
      },
      {
        name: 'Image Alt-Text',
        owner: 'Kimmy',
        ownerPath: A.kimmy,
        maturity: 60,
        spec: {
          purpose: 'Descriptive, localised alt on every image for SEO + a11y.',
          scope: 'All <img> alt, gallery.alts[].',
          triggers: 'During page build + seo:write.',
          inputs: 'Image context.',
          steps: 'Write per-image alt → localise → store in i18n / seo overrides.',
          outputs: 'Alt text on every image.',
          variants: 'Product vs gallery vs hero.',
          guardrails: 'No empty/placeholder alt; localised per locale.',
          integrations: 'seo:write overrides.',
          completion: 'No missing alt in audit.',
          examples: 'gallery.alts arrays.',
          openItems: 'Alt generation partly manual.',
        },
        docs: [CLAUDE, SETUP],
      },
    ],
  },

  // ── LAYER 4 ──────────────────────────────────────────────────────────────
  {
    id: 4,
    name: 'Page-Section Library',
    subtitle: 'The reusable homepage stack, mirrored on location pages.',
    phase: 'BUILD',
    units: [
      {
        name: 'Site Chrome Components',
        owner: 'Kimmy',
        ownerPath: A.kimmy,
        maturity: 90,
        spec: {
          purpose: 'Header + footer + fomo + switcher rendered identically everywhere.',
          scope: 'SiteHeader, SiteFooter, FomoBanner, LanguageSwitcher.',
          triggers: 'Every public page.',
          inputs: 'Brand + locale labels.',
          steps: 'Render shared chrome on home / location / blog.',
          outputs: 'Consistent chrome.',
          variants: 'None.',
          guardrails: 'FOMO red/black + live countdown; switcher pills via useId().',
          integrations: 'All routes.',
          completion: '*-chrome checks pass.',
          examples: 'templates/site-chrome.',
          openItems: '—',
        },
        docs: [FLOW, CHROME, GUARD],
      },
      {
        name: 'Hero',
        owner: 'Kagura',
        ownerPath: A.kagura,
        maturity: 80,
        spec: {
          purpose: 'Above-the-fold conversion: H1 + H2 + WhatsApp CTA.',
          scope: 'Hero section.',
          triggers: 'Top of every page.',
          inputs: 'Brand image, copy, CTA.',
          steps: 'logo → eyebrow → H1 → H2 → support → CTA row → stats.',
          outputs: 'Hero with gradient-overlaid brand bg.',
          variants: 'Home hero vs smaller location hero.',
          guardrails: 'Exactly one H1 + one H2; PNG cutout via plain <img>.',
          integrations: 'WhatsApp routing.',
          completion: 'homepage-h1-h2 passes.',
          examples: 'Per-project hero.',
          openItems: '—',
        },
        docs: [FLOW, CLAUDE, agentDoc(A.kagura, 'Kagura')],
      },
      {
        name: 'USP Bar',
        owner: 'Kagura',
        ownerPath: A.kagura,
        maturity: 85,
        spec: {
          purpose: 'Three-point trust panel directly below the hero.',
          scope: '3-cell .usp-panel.',
          triggers: 'Mandatory on every homepage.',
          inputs: 'Three USP strings (localised).',
          steps: 'Render 3 cells → SEO-only hidden H3.',
          outputs: 'USP bar.',
          variants: 'Home vs location copy.',
          guardrails: 'Mandatory; localised; mirrored on location pages.',
          integrations: 'i18n.',
          completion: 'Present on home + location.',
          examples: 'usp.home / usp.location keys.',
          openItems: '—',
        },
        docs: [CLAUDE, FLOW],
      },
      {
        name: 'Products Grid (dynamic)',
        owner: 'Cyclops',
        ownerPath: A.cyclops,
        maturity: 85,
        spec: {
          purpose: 'Render products live from Supabase, auto-fitting any count.',
          scope: 'products + product_photos via webcore.',
          triggers: 'Home + location pages.',
          inputs: 'DB rows for this website.',
          steps: 'Query active products → grid auto-fill → per-card WhatsApp CTA.',
          outputs: 'Dynamic product grid.',
          variants: '1, 6 or 20 products.',
          guardrails: 'Never hardcode products; grid leaves no blank slot.',
          integrations: 'Webcore + WhatsApp.',
          completion: 'Adding a DB row appears within revalidate.',
          examples: 'Electrician services grid.',
          openItems: '—',
        },
        docs: [CLAUDE, agentDoc(A.cyclops, 'Cyclops')],
      },
      {
        name: 'Special Section (project-unique)',
        owner: 'Kagura',
        ownerPath: A.kagura,
        maturity: 52,
        spec: {
          purpose: 'One bespoke section that makes each site feel distinct.',
          scope: 'Project-specific component.',
          triggers: 'Per Kagura design direction.',
          inputs: 'Industry insight.',
          steps: 'Design a unique section → build → localise.',
          outputs: 'Distinct on-brand section.',
          variants: 'Calculator, coverage map, comparison, etc.',
          guardrails: 'Must differ from other sites; tokenised.',
          integrations: 'Design direction.',
          completion: 'Section is unique + functional.',
          examples: 'Cost estimate / coverage variants.',
          openItems: 'No library of special sections yet.',
        },
        docs: [agentDoc(A.kagura, 'Kagura'), FLOW],
      },
      {
        name: 'Mid Sections (Process / Why / Reviews / Gallery / FAQ)',
        owner: 'Kimmy',
        ownerPath: A.kimmy,
        maturity: 75,
        spec: {
          purpose: 'The proof + trust + answers stack between products and CTA.',
          scope: 'How-it-works, why-us, reviews, gallery, FAQ.',
          triggers: 'Homepage + mirrored on location.',
          inputs: 'Copy + review schema + gallery images.',
          steps: 'Build each section → localise → mirror on location pages.',
          outputs: 'Full mid-page stack.',
          variants: 'Per-locale copy.',
          guardrails: 'Gallery no blank slots; Google review icons; mirrored on location.',
          integrations: 'Review schema.',
          completion: 'location-matches-homepage passes.',
          examples: 'Per-project sections.',
          openItems: '—',
        },
        docs: [FLOW, CLAUDE],
      },
      {
        name: 'WhatsApp CTAs + Final CTA',
        owner: 'Kimmy',
        ownerPath: A.kimmy,
        maturity: 88,
        spec: {
          purpose: 'Multiple recognisable conversion points routed through the redirect.',
          scope: 'Nav, hero, product cards, inline, FAB, final CTA, blog banner.',
          triggers: 'Throughout the page.',
          inputs: 'waRedirect link + locale.',
          steps: 'Render official-green WA buttons with the glyph everywhere.',
          outputs: '≥3 WhatsApp CTAs per page.',
          variants: 'Button vs FAB vs banner.',
          guardrails: 'Official green #25D366; white glyph; ≤3-word labels; route via /redirect-whatsapp-1.',
          integrations: 'Leads routing + tracking.',
          completion: 'homepage-product-ctas + blog-post-cta-banner pass.',
          examples: 'Electrician CTA fixes.',
          openItems: '—',
        },
        docs: [CLAUDE, GUARD, agentDoc(A.kimmy, 'Kimmy')],
      },
      {
        name: 'Location Pages (mirror homepage)',
        owner: 'Kimmy',
        ownerPath: A.kimmy,
        maturity: 78,
        spec: {
          purpose: 'Same layout as home, only the copy localised per city.',
          scope: 'app/[locale]/{product}/[location].',
          triggers: 'generateStaticParams over all towns.',
          inputs: 'Location copy + shared sections.',
          steps: 'Render same section stack with same class names → unique city copy + FAQs.',
          outputs: 'One page per town.',
          variants: 'Breadcrumb / city-chip / nearby-card only.',
          guardrails: 'Never drop USP / gallery / reviews; unique copy; dynamic phone.',
          integrations: 'Hub-spoke SEO.',
          completion: 'location-matches-homepage passes.',
          examples: '/electrician-service/[location].',
          openItems: 'Some projects ship stripped location pages.',
        },
        docs: [CLAUDE, FLOW],
      },
      {
        name: 'Blog Layout',
        owner: 'Hanabi',
        ownerPath: A.hanabi,
        maturity: 80,
        spec: {
          purpose: 'Canonical listing + article layout matching the reference.',
          scope: 'blog/page.tsx, blog/[slug]/page.tsx.',
          triggers: 'Blog enabled.',
          inputs: 'blog_posts + blog_translations.',
          steps: 'Listing card grid → article ≤740px + sticky recent + ToC + bottom WA CTA.',
          outputs: 'Live blog pages.',
          variants: 'Listing vs article.',
          guardrails: 'Same chrome (no BlogNav); WA CTA banner with glyph.',
          integrations: 'Webcore blog reads.',
          completion: 'blog-listing-chrome + blog-post-chrome pass.',
          examples: 'electric-wheelchair canonical blog.',
          openItems: '—',
        },
        docs: [agentDoc(A.hanabi, 'Hanabi'), BLOGTPL, FLOW],
      },
    ],
  },

  // ── LAYER 5 ──────────────────────────────────────────────────────────────
  {
    id: 5,
    name: 'SEO Scale',
    subtitle: 'Programmatic local SEO across every town.',
    phase: 'BUILD',
    units: [
      {
        name: 'Dynamic Location Pages (hub-spoke)',
        owner: 'Sora',
        ownerPath: A.sora,
        maturity: 85,
        spec: {
          purpose: 'Hub-and-spoke local SEO over 150–180 towns.',
          scope: 'generateStaticParams, internal links.',
          triggers: 'Build time.',
          inputs: 'locations config + copy.',
          steps: 'Emit a page per town → interlink hub ↔ spokes + nearby.',
          outputs: 'Full local-SEO surface.',
          variants: 'Per-state grouping.',
          guardrails: 'Every town has a page + sitemap entry; unique copy.',
          integrations: 'Sitemap.',
          completion: 'All towns reachable + indexed.',
          examples: 'Per-project location tree.',
          openItems: '—',
        },
        docs: [agentDoc(A.sora, 'Sora'), CLAUDE],
      },
      {
        name: 'Sitemap & Robots',
        owner: 'Kimmy',
        ownerPath: A.kimmy,
        maturity: 85,
        spec: {
          purpose: 'Expose every route to crawlers.',
          scope: 'app/sitemap.ts, app/robots.ts.',
          triggers: 'Build.',
          inputs: 'siteConfig.domain + routes.',
          steps: 'Generate sitemap of all locales/towns/blog → robots.',
          outputs: 'sitemap.xml + robots.txt.',
          variants: 'Per-locale alternates.',
          guardrails: 'Base URL = served domain; all towns included.',
          integrations: 'GSC submit.',
          completion: 'sitemap.xml serves 200.',
          examples: 'Per-project sitemap.ts.',
          openItems: '—',
        },
        docs: [SETUP, CLAUDE],
      },
      {
        name: 'Schema Markup',
        owner: 'Kimmy',
        ownerPath: A.kimmy,
        maturity: 80,
        spec: {
          purpose: 'Structured data for rich results.',
          scope: 'LocalBusiness, Product, FAQ, Breadcrumb, Organization schema.',
          triggers: 'Per relevant page.',
          inputs: 'Business + product + FAQ data.',
          steps: 'Render JSON-LD components per page type.',
          outputs: 'Valid schema on each route.',
          variants: 'Per page type.',
          guardrails: 'Base URL = served domain; schema where relevant.',
          integrations: 'Rich results.',
          completion: 'Schema validates.',
          examples: 'components/schema/*.',
          openItems: '—',
        },
        docs: [SETUP, CLAUDE],
      },
      {
        name: 'Programmatic SEO Content',
        owner: 'Sora',
        ownerPath: A.sora,
        maturity: 58,
        spec: {
          purpose: 'Scale unique-enough content across towns + topics.',
          scope: 'Location copy templates + variation.',
          triggers: 'Content generation.',
          inputs: 'Keyword plan + town list.',
          steps: 'Template + vary per city to avoid duplication.',
          outputs: 'Scaled local content.',
          variants: 'City / service permutations.',
          guardrails: 'Avoid thin/duplicate content.',
          integrations: 'Copy pipeline.',
          completion: 'No duplicate-content flags.',
          examples: 'copy-locations.md.',
          openItems: 'Generation still semi-manual.',
        },
        docs: [agentDoc(A.sora, 'Sora'), CLAUDE],
      },
    ],
  },

  // ── LAYER 6 ──────────────────────────────────────────────────────────────
  {
    id: 6,
    name: 'Conversion & Webcore Data',
    subtitle: 'Phase 2 — write data + route every lead through WhatsApp.',
    phase: 'DATA',
    units: [
      {
        name: 'WhatsApp Routing & Leads Modes',
        owner: 'Cyclops',
        ownerPath: A.cyclops,
        maturity: 90,
        spec: {
          purpose: 'Pick the right phone per click and forward to wa.me.',
          scope: 'redirect-whatsapp-1, phone_numbers, company_websites.',
          triggers: 'Every WhatsApp click.',
          inputs: 'Host, location slug, leads_mode.',
          steps: 'Read mode → filter numbers → weighted pick → build wa.me URL.',
          outputs: 'Routed WhatsApp deep link.',
          variants: 'single / rotation / location / hybrid.',
          guardrails: 'Always via redirect page; never bare wa.me; tracked first.',
          integrations: 'Supabase + tracking.',
          completion: 'Mode logic returns a live number.',
          examples: 'Hybrid regional routing.',
          openItems: '—',
        },
        docs: [CLAUDE, SETUP, agentDoc(A.cyclops, 'Cyclops')],
      },
      {
        name: 'Webcore Writes (products / phones / blog / seo)',
        owner: 'Cyclops',
        ownerPath: A.cyclops,
        maturity: 80,
        spec: {
          purpose: 'Scoped API writes instead of raw service-role SQL.',
          scope: 'POST /api/public/products | phone-numbers | blog; /api/seo/overrides.',
          triggers: 'Phase 2 data step.',
          inputs: 'X-API-Key + website.',
          steps: 'Write products → phones → blog → seo overrides.',
          outputs: 'DB rows scoped to the website.',
          variants: 'products:write / phones:write / blog:write / seo:write.',
          guardrails: 'website = the served domain; no service-role key needed.',
          integrations: 'Webcore API.',
          completion: 'Rows visible to the live site.',
          examples: 'Seeding default phone + products.',
          openItems: '—',
        },
        docs: [FLOW, SETUP],
      },
      {
        name: 'Blog Generation',
        owner: 'Hanabi',
        ownerPath: A.hanabi,
        maturity: 78,
        spec: {
          purpose: 'Generate SEO articles + insert into Supabase.',
          scope: 'blog_posts + blog_translations.',
          triggers: 'After deploy-ready (any time).',
          inputs: 'Topic + keyword plan.',
          steps: 'Write H1→H2→H3→p with backlinks + alt → insert ≥10 posts.',
          outputs: 'Published localized articles.',
          variants: 'Per-locale translations.',
          guardrails: 'Heading hierarchy; internal backlinks; excerpt + meta.',
          integrations: 'blog:write + admin CMS.',
          completion: 'Live /blog renders posts.',
          examples: '10 roller-shutter articles.',
          openItems: '—',
        },
        docs: [agentDoc(A.hanabi, 'Hanabi'), CLAUDE],
      },
      {
        name: 'Click Tracking',
        owner: 'Kimmy',
        ownerPath: A.kimmy,
        maturity: 74,
        spec: {
          purpose: 'Record every WhatsApp click + product impression.',
          scope: 'data-website, webcore t.js, uwc() events.',
          triggers: 'On click / impression.',
          inputs: 'Served domain (data-website).',
          steps: 'Load t.js → fire uwc("click"|"impression") → land in the live bucket.',
          outputs: 'Analytics events.',
          variants: 'click / impression labels.',
          guardrails: 'data-website must resolve to the LIVE domain.',
          integrations: 'Webcore analytics.',
          completion: 'whatsapp-click-track passes; events land.',
          examples: 'data-website domain-match fix.',
          openItems: '—',
        },
        docs: [TRACK, GUARD],
      },
    ],
  },

  // ── LAYER 7 ──────────────────────────────────────────────────────────────
  {
    id: 7,
    name: 'Launch, Guardrails & Analytics',
    subtitle: 'Phase 3 — the 101-check spine, deploy, and Google.',
    phase: 'SHIP',
    units: [
      {
        name: 'Guardrail Gate (101 checks)',
        owner: 'Layla',
        ownerPath: A.layla,
        maturity: 90,
        spec: {
          purpose: 'Deterministic enforcement of all 101 mechanical rules.',
          scope: 'utopia-wizard checkMeta.ts + checklist.ts (55 blocking / 46 advisory).',
          triggers: 'Self-check, pre-commit, CI, deploy.',
          inputs: 'Project source + live status.',
          steps: 'npm run gate → score 0–100 → block on failures.',
          outputs: 'Score + blocking list.',
          variants: '--source-only / --ratchet / --regression-only.',
          guardrails: 'Machine owns the mechanical 101; humans judge taste.',
          integrations: 'guardrails.html render.',
          completion: 'Zero blocking failures.',
          examples: 'Every agent self-verifies via the gate.',
          openItems: '—',
        },
        docs: [FLOW, GUARD, SELFCHK],
      },
      {
        name: 'vercel-domain-match',
        owner: 'Layla',
        ownerPath: A.layla,
        maturity: 85,
        spec: {
          purpose: 'Catch "config says one domain, Vercel serves another".',
          scope: 'config/site.ts vs Vercel API alias.',
          triggers: 'Full gate / ship.',
          inputs: 'VERCEL_TOKEN.',
          steps: 'Ask Vercel which alias is served → compare → fail on mismatch.',
          outputs: 'Pass/fail verdict.',
          variants: '—',
          guardrails: 'Blocks deploy on mismatch.',
          integrations: 'Vercel API.',
          completion: 'Config domain == served alias.',
          examples: 'roller-shutter domain fix.',
          openItems: '—',
        },
        docs: [FLOW, GUARD],
      },
      {
        name: 'CI guardrails-gate + ratchet',
        owner: 'Layla',
        ownerPath: A.layla,
        maturity: 85,
        spec: {
          purpose: 'Re-run the gate on changed projects; block score regressions.',
          scope: 'pre-commit hook + GitHub Actions.',
          triggers: 'Commit + PR.',
          inputs: 'Changed projects + snapshot.',
          steps: 'pre-commit (source-only) → CI ratchet vs last snapshot.',
          outputs: 'Merge gate verdict.',
          variants: 'regression-only mode.',
          guardrails: 'No score regression vs snapshot.',
          integrations: 'GitHub Actions + snapshots.',
          completion: 'CI green before merge.',
          examples: 'guardrails-gate workflow.',
          openItems: '—',
        },
        docs: [FLOW, GUARD],
      },
      {
        name: 'Visual QA (screenshots ≥2 rounds)',
        owner: 'Kagura',
        ownerPath: A.kagura,
        maturity: 64,
        spec: {
          purpose: 'Catch layout/spacing/colour issues the gate can’t see.',
          scope: 'serve.mjs + screenshot.mjs.',
          triggers: 'Before Gate 1.',
          inputs: 'Running localhost.',
          steps: 'dev → screenshot → compare → fix → re-shoot (≥2 rounds, desktop+mobile, 3 locales).',
          outputs: 'Verified visuals.',
          variants: 'Desktop / mobile / per-locale.',
          guardrails: 'Mobile-first; center elements; never screenshot file:// URLs.',
          integrations: 'Puppeteer.',
          completion: 'Two clean comparison rounds.',
          examples: 'temporary screenshots/.',
          openItems: 'No automated visual diff.',
        },
        docs: [CLAUDE, FLOW, agentDoc(A.kagura, 'Kagura')],
      },
      {
        name: 'Favicons / OG Images',
        owner: 'Kimmy',
        ownerPath: A.kimmy,
        maturity: 66,
        spec: {
          purpose: 'Launch polish: favicon + social share images.',
          scope: 'app/icon.svg, OG image, manifest.',
          triggers: 'Pre-deploy.',
          inputs: 'Logo + hero.',
          steps: 'Generate favicon + OG → wire metadata.',
          outputs: 'Share-ready assets.',
          variants: 'Per-locale OG optional.',
          guardrails: 'Preflight blocks deploy missing OG.',
          integrations: 'Metadata + manifest.',
          completion: 'OG + favicon present.',
          examples: 'Per-project public assets.',
          openItems: 'OG generation partly manual.',
        },
        docs: [SETUP, CLAUDE],
      },
      {
        name: 'Deploy (Layla → Vercel)',
        owner: 'Layla',
        ownerPath: A.layla,
        maturity: 86,
        spec: {
          purpose: 'Integration-test, push, deploy — refuse on any blocking failure.',
          scope: 'GitHub push + vercel --prod.',
          triggers: 'After both gates.',
          inputs: 'Clean gate + ratchet.',
          steps: 'Verify phone system → push → CI gate → deploy → alias.',
          outputs: 'Live aliased production site.',
          variants: 'Preview vs production.',
          guardrails: 'Layla refuses to deploy on blocking failure.',
          integrations: 'Vercel + CI.',
          completion: 'Deploy URL responds; alias served.',
          examples: 'Electrician / roller-shutter deploys.',
          openItems: '—',
        },
        docs: [agentDoc(A.layla, 'Layla'), FLOW, SETUP],
      },
      {
        name: 'Monitor (scan / snapshots)',
        owner: 'Layla',
        ownerPath: A.layla,
        maturity: 82,
        spec: {
          purpose: 'Continuously score every project + surface drift.',
          scope: 'npm run scan → monitor_snapshots → the Monitor tab.',
          triggers: 'Scheduled + manual rescan.',
          inputs: 'All projects under projects/.',
          steps: 'Run checklist per project → upsert snapshot → render Monitor.',
          outputs: 'Per-project score + group breakdown.',
          variants: 'Live vs source-only.',
          guardrails: 'Snapshot is the ratchet baseline.',
          integrations: 'Supabase + this wizard.',
          completion: 'Snapshots fresh for all projects.',
          examples: 'The Monitor tab in this app.',
          openItems: '—',
        },
        docs: [FLOW, GUARD],
      },
      {
        name: 'Google Connect (GA4 / GTM / GSC)',
        owner: 'Human',
        ownerPath: A.human,
        maturity: 38,
        spec: {
          purpose: 'One-time OAuth consent linking the site to Google.',
          scope: 'Admin UI connect flow.',
          triggers: 'After deploy.',
          inputs: 'Google account consent.',
          steps: '[human] connect GSC / GA4 / GTM in the admin UI.',
          outputs: 'Connected analytics.',
          variants: 'Per-property.',
          guardrails: 'API key cannot do this — human consent required.',
          integrations: 'Google OAuth.',
          completion: 'Site shows connected in admin.',
          examples: 'Admin integrations panel.',
          openItems: 'Fully manual; not automatable.',
        },
        docs: [SETUP, TRACK],
      },
      {
        name: 'Sitemap Submit + Key Events',
        owner: 'Layla',
        ownerPath: A.layla,
        maturity: 55,
        spec: {
          purpose: 'After connect, submit sitemap + mark conversion events via API.',
          scope: 'integrations:write endpoints.',
          triggers: 'After Google connect.',
          inputs: 'Connected property.',
          steps: 'POST submit-sitemap → mark-key-event whatsapp_click.',
          outputs: 'Submitted sitemap + key event.',
          variants: '—',
          guardrails: 'Mark key event only after it has fired once.',
          integrations: 'GSC + Marketing API.',
          completion: 'Sitemap submitted; key event marked.',
          examples: 'whatsapp_click as key event.',
          openItems: 'Depends on manual connect first.',
        },
        docs: [SETUP, TRACK],
      },
      {
        name: 'Backlinks / Off-page',
        owner: 'Sora',
        ownerPath: A.sora,
        maturity: 25,
        spec: {
          purpose: 'Off-page authority building.',
          scope: 'External backlinks + citations.',
          triggers: 'Post-launch ops.',
          inputs: 'Live site + niche.',
          steps: 'Plan + acquire citations/backlinks.',
          outputs: 'Authority signals.',
          variants: 'Local citations vs editorial.',
          guardrails: 'No spammy link schemes.',
          integrations: 'External.',
          completion: 'Backlink plan executed.',
          examples: '—',
          openItems: 'No system yet — biggest gap.',
        },
        docs: [agentDoc(A.sora, 'Sora'), SETUP],
      },
    ],
  },
]

// ── Derived stats ──────────────────────────────────────────────────────────
export type Band = 'mature' | 'partial' | 'gap'

export function band(maturity: number): Band {
  if (maturity >= 75) return 'mature'
  if (maturity >= 45) return 'partial'
  return 'gap'
}

export const ALL_UNITS = LAYERS.flatMap((l) => l.units)

export const STATS = {
  totalUnits: ALL_UNITS.length,
  totalLayers: LAYERS.length,
  avg: Math.round(
    ALL_UNITS.reduce((s, u) => s + u.maturity, 0) / ALL_UNITS.length,
  ),
  mature: ALL_UNITS.filter((u) => band(u.maturity) === 'mature').length,
  partial: ALL_UNITS.filter((u) => band(u.maturity) === 'partial').length,
  gap: ALL_UNITS.filter((u) => band(u.maturity) === 'gap').length,
}

export function layerAvg(layer: Layer): number {
  return Math.round(
    layer.units.reduce((s, u) => s + u.maturity, 0) / layer.units.length,
  )
}

// ── Agent roster (for the per-agent view) ───────────────────────────────────
export const AGENT_ROLES: Record<string, { role: string; path: string }> = {
  Alpha: { role: 'System Architect', path: A.alpha },
  Cyclops: { role: 'Database Engineer', path: A.cyclops },
  Sora: { role: 'SEO Strategist', path: A.sora },
  Nana: { role: 'Copywriter', path: A.nana },
  Kagura: { role: 'UI Design Specialist', path: A.kagura },
  Kimmy: { role: 'Technical Implementation', path: A.kimmy },
  Hanabi: { role: 'Blog Writer', path: A.hanabi },
  Layla: { role: 'QA & Deployment', path: A.layla },
  Human: { role: 'Manual / human step', path: A.human },
}

export interface AgentSummary {
  name: string
  role: string
  path: string
  count: number
  avg: number
}

// Preserve the roster order above, but only include owners that actually own units.
export const AGENT_SUMMARY: AgentSummary[] = Object.keys(AGENT_ROLES)
  .map((name) => {
    const owned = ALL_UNITS.filter((u) => u.owner === name)
    return {
      name,
      role: AGENT_ROLES[name].role,
      path: AGENT_ROLES[name].path,
      count: owned.length,
      avg: owned.length
        ? Math.round(owned.reduce((s, u) => s + u.maturity, 0) / owned.length)
        : 0,
    }
  })
  .filter((a) => a.count > 0)

export const SPEC_FIELDS: { key: keyof UnitSpec; label: string }[] = [
  { key: 'purpose', label: 'Purpose' },
  { key: 'scope', label: 'Scope' },
  { key: 'triggers', label: 'Triggers' },
  { key: 'inputs', label: 'Inputs' },
  { key: 'steps', label: 'Steps' },
  { key: 'outputs', label: 'Outputs' },
  { key: 'variants', label: 'Variants' },
  { key: 'guardrails', label: 'Guardrails' },
  { key: 'integrations', label: 'Integrations' },
  { key: 'completion', label: 'Completion' },
  { key: 'examples', label: 'Examples' },
  { key: 'openItems', label: 'Open items' },
]
