import { siteConfig } from '@/config/site';

/**
 * Social share card — a 1200x630 screenshot of the hero section, one per locale
 * (`public/og-{locale}.png`), generated by `scripts/og-shot.mjs`.
 *
 * Regenerate after ANY hero copy / image / palette change. The card is a
 * screenshot, so a stale one is invisible: the site looks right and only the
 * shared link is wrong.
 *
 * Relative URLs resolve against the `metadataBase` set in
 * app/[locale]/layout.tsx from `siteConfig.siteUrl`. (The one in the ROOT
 * app/layout.tsx is a stale copy-paste pointing at another site entirely — the
 * [locale] layout overrides it for every page under it, which is why cards
 * still resolve correctly.)
 *
 * Next.js replaces a parent's `openGraph` object WHOLESALE when a page defines
 * its own, so every page that sets `openGraph` must spread this in explicitly.
 * Inheriting it from the layout does NOT work — that is exactly how sites ship
 * with a share card on the homepage and none on location or blog pages.
 */
export function ogImage(locale: string, alt?: string) {
  const known = (siteConfig.locales as readonly string[]).includes(locale);
  return {
    url: `/og-${known ? locale : siteConfig.defaultLocale}.png`,
    width: 1200,
    height: 630,
    alt: alt ?? siteConfig.brandName,
  };
}

/**
 * Ready-to-spread `images` array for `openGraph` / `twitter`.
 * `alt` is optional so a page can describe its own card (the homepage and
 * location pages pass their translated `meta.ogImageAlt`).
 */
export function ogImages(locale: string, alt?: string) {
  return [ogImage(locale, alt)];
}
